ShowFeatureVisibility.label=Show features visibility
ShowFeatureVisibility.tooltip=Show features visibility (operations, attributes, associations)
ShowNameSpaceVisibility.label=Show namespaces visibility
ShowNameSpaceVisibility.tooltip=Show namespaces visibility (packages, classes, interfaces...)
ShowTechnicalComponent.label=Show libraries
ShowTechnicalComponent.tooltip=Show libraries (modules, predefined types...)
