# res is needed in source to make automatic tests to succeed
source.. = src/,\
           res/
output.. = bin/

javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               res/,\
               lib/org.hsqldb.hsqldb-2.7.1-debug.jar
