source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,plugin_fr.properties,\
               e4model/,\
               icons/,\
               res/
