// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

= Copyright agreement

Information in this on-line help is subject to change without notice and does not represent a commitment on the part of Docaposte. The software described in this on-line help is provided under a license agreement. The software may be used or copied only in accordance with the terms of the agreement. It is against the law to copy the software on any medium except as specifically allowed in the license agreement. The purchaser may make one copy of the software for backup purposes. No part of this on-line help may be reproduced or transmitted in any form or by means, electronic or mechanical, including photocopying, recording, or information storage and retrieval systems, for any purpose other than the purchaser's personal use, without the express written consent of Docaposte.

Modelio is a registered trademark of Docaposte.

This product includes software developed by the Apache Software Foundation (http://www.apache.org/).

ML and OMG are registered trademarks of the Object Management Group. All other company or product names are trademarks or registered trademarks of their respective owners.


