/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* WARNING: GENERATED FILE -  DO NOT EDIT
     Metamodel: Archimate, version 1.0.4, by Modeliosoft
     Generator version: 3.14.00
     Generated on: Feb 9, 2023
*/
package org.modelio.archimate.metamodel.layers.application.behavior;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import org.modelio.archimate.metamodel.core.generic.Event;

/**
 * ApplicationEvent vnull
 *
 *
 * <p>An application event is an application behavior element that denotes a state change.</p><p>Application functions and other application behavior may be triggered or interrupted by an&nbsp;application event. Also, application behavior may raise events that trigger other application&nbsp;behavior. Unlike processes, functions, and interactions, an event is instantaneous; it does not&nbsp;have duration. Events may originate from the environment of the organization (e.g., from an&nbsp;external application), but also internal events may occur generated by, for example, other&nbsp;applications within the organization.</p><p>An application event may have a time attribute that denotes the moment or moments at which&nbsp;the event happens. For example, this can be used to model time schedules; e.g., an event that&nbsp;triggers a daily batch process.</p><p>An application event may trigger or be triggered (raised) by an application function, process, or&nbsp;interaction. An application event may access a data object and may be composed of other&nbsp;application events. The name of an application event should preferably be a verb in the perfect</p><p>tense; e.g., &#8220;claim received&#8221;.</p>
 *
 *
 */
@objid ("0da38155-2e76-4b3d-a333-76dde24fa726")
public interface ApplicationEvent extends Event {
    /**
     * The metaclass simple name.
     */
    @objid ("d0ecf3ce-c028-4532-a789-e9bd34bbc92d")
    public static final String MNAME = "ApplicationEvent";

    /**
     * The metaclass qualified name.
     */
    @objid ("31e50bba-4ad9-4d21-9060-0f9c23dfcf93")
    public static final String MQNAME = "Archimate.ApplicationEvent";

}
