<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.modeliosoft.modelio</groupId>
	<artifactId>modelio-library</artifactId>
	<version>6.2.0.00</version>
	<packaging>pom</packaging>

	<properties>
		<modelio.version>[6.2.0,6.2.1)</modelio.version>
		<svnkit.version>1.10.9</svnkit.version>
	</properties>

	<repositories>
		<repository>
			<id>svnkit</id>
			<url>http://maven.tmatesoft.com/content/repositories/releases</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.project</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.core.project.svn</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.utils</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.project.data</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.session</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.kernel</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.core.project.cms.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.store.exml</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.version</artifactId>
			<version>${modelio.version}</version>
		</dependency>

		<!-- EMF API/IMPL -->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.metamodel.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.core.metamodel.impl</artifactId>
			<version>${modelio.version}</version>
		</dependency>

		<!-- BPMN API/IMPL -->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.bpmn.metamodel.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.bpmn.metamodel.implementation</artifactId>
			<version>${modelio.version}</version>
		</dependency>

		<!-- Analyst API/IMPL + Scope-->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.analyst.metamodel.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.analyst.metamodel.implementation</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.analyst.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>

		<!-- ArchiMate -->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.archimate.metamodel.api</artifactId>
			<version>${modelio.version}</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.archimate.metamodel.implementation</artifactId>
			<version>${modelio.version}</version>
		</dependency>

		<!-- Other libraries dependencies-->
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.10</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.12</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<version>2.9.0</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<version>2.9.0</version>
		</dependency>
		<dependency>
			<groupId>org.tmatesoft.svnkit</groupId>
			<artifactId>svnkit</artifactId>
			<version>${svnkit.version}</version>
		</dependency>
		<dependency>
			<groupId>jdbm</groupId>
			<artifactId>jdbm</artifactId>
			<version>2.4.0</version>
		</dependency>
		<dependency>
			<groupId>net.sf.practicalxml</groupId>
			<artifactId>practicalxml</artifactId>
			<version>1.1.13</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.eclipse.osgi</artifactId>
			<version>3.16.100.v20201030-1916</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.eclipse.core.runtime</artifactId>
			<version>3.20.0.v20201027-1526</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.eclipse.equinox.common</artifactId>
			<version>3.14.0.v20201102-2053</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
			<version>1.18</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- compute and copy dependencies in a local target/lib directory to
				 be used by the agent aggregator -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-deps</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<inherited>true</inherited>
						<configuration>
							<outputDirectory>${basedir}/lib</outputDirectory>
							<copyPom>false</copyPom>
							<includeGroupIds>org.modelio,com.modeliosoft.modelio,com.modelio,jdbm,net.sf.practicalxml,org.apache</includeGroupIds>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<archive>
						<addMavenDescriptor>false</addMavenDescriptor>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
