source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               res/,\
               e4model/,\
               plugin.properties,plugin_fr.properties
