source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               e4model/,\
               fragment.properties,fragment_fr.properties,\
               fragment.xml,\
               res/,\
               images/,\
               plugin_customization.ini
