// Disable all captions for figures.
:!figure-caption:
// Path to the stylesheet files
:stylesdir: .

= Command line options

=== Command Line Modelio

To run Modelio in command line, you must execute:

* In Windows: +
The executable file modelio.exe located in Modelio's installation folder.
* In Linux: +
The executable file modelio.sh located in Modelio's installation folder.
* In MacOSX: +
The executable file modelio.sh located in the Contents/MacOS subdirectory of Modelio's installation folder.

In this page, we will refer to Modelio's executable full path (for example: C:\Program Files\Modelio\modelio.exe), as *$\{MODELIO_EXE}*.

=== Options list

Modelio comes with several command line options:

*-workspace* _workspacePath_ +
Indicates the workspace to use.

For example:

* Open Modelio in using C:\Users\user\myWorkspace directory as workspace . +
$\{MODELIO_EXE} *-workspace* _C:\Users\user\myWorkspace_

*-mserver* saasServerUrl +
Sets a default server value for the login window.

For example:

* Open Modelio using _\https://modelioserver.mycompany.com/_ address as saasServer . +
$\{MODELIO_EXE} *-mserver* _\https://modelioserver.mycompany.com/_

*-muser* _login_ +
Sets a default login value for the login window.

For example:

* Open Modelio SaaS using User1 as login . +
$\{MODELIO_EXE} *-muser* _User1_

//*-create* _projectName_ +
//Creates a project named _projectName_ in the workspace. Must not be used at the same time as "-project". +
//For example:
//
//* Create a new project named "MyNewProject": +
//$\{MODELIO_EXE} *-create* _MyNewProject_
//* Create a new project named "AnotherNewProject" in the C:\Users\user\myWorkspace workspace : +
//$\{MODELIO_EXE} *-workspace* _C:\Users\user\myWorkspace_ *-create* _MyNewProject_
//
//*-template* templateName +
//This option must be used with "-create". It Indicates a project type to use when creating a new project. +
//_templateName_ can be a full path to the project type (extension file is .template) or only a project type name. In the latter case, the project type file must be present in the "templates" directory of the Modelio installation. +
//For example:
//
//* Create a new project named "MyProject" using the "UML" project type which is present in the Modelio installation: $\{MODELIO_EXE} +
//$\{MODELIO_EXE} *-create* _MyProject_ *-template* _UML_
//* _Create a new project named "MyNewProject" using the C:\Users\user\myTemplate.template file as project type: +
//$\{MODELIO_EXE} *-create* _MyNewProject_ *-template* _C:\Users\user\myTemplate.template_

*-project* _projectName_ or *-open* _projectName_ +
Indicates which project to open. +
//Must not be used at the same time as "-create". +
Needs to specify a login and token to access a server project, see example below.

For example:

* Open a Modelio local project named "MyProject": +
$\{MODELIO_EXE} *-project* _MyProject_
* Open a Modelio local project named "AnotherProject" in the C:\Users\user\myWorkspace workspace : +
$\{MODELIO_EXE} *-workspace* _C:\Users\user\myWorkspace_ *-project* _AnotherProject_

*-join* _projectID_ +
Join the project which ID is _projectID_. +
Needs to specify a server, user and token, see example below.

To get this identifier:

. log into your server with Modelio
. click on the project for details
. look for the _'Project identifier'_ property

*-musertoken* _token_ +
Use this credentials combined with the *-muser* option when opening or joining a Modelio Server project.

To get the user token:

. log into Modelio Server with a web browser
. on the top right, edit your user information
. generate a token if necessary
. use the _'save token'_ button to download the token value

Examples:

* Join a Modelio Server project as "user1". +
$\{MODELIO_EXE} *-join* _12_ *-mserver* _\https://modelioserver.mycompany.com/_ *-muser* _user1_ *-musertoken* _user1_token_
* Open a Modelio Server project named "MyProject" as "user1". +
$\{MODELIO_EXE} *-project* _MyProject_ *-muser* _user1_ *-musertoken* _user1_token_

*-batch* _scriptFile_ +
Indicates a Jython script to launch automatically after opening a project. Modelio will close automatically after script execution. Must be used with "-project" or "-join".

For example:

* Open the "MyProject" project and run the "C:\Users\user\myscript.py" Jython script on it. +
$\{MODELIO_EXE} *-project* _MyProject_ *-batch* _C:\Users\user\myscript.py_

*-param* _key val_ +
Set the key variable with the val value. This variable is available in the jython script.

For example:

* Run the " C:\Users\user\myscript.py " Jython script on the "MyProject" project and set two variables "myVar1" and "myVar2" and having respectively the values "the value1" and "the value2": +
$\{MODELIO_EXE} *-project* _MyProject_ *-batch* _C:\Users\user\myscript.py_ *-param* _myVar1_ " _the value1_ " *-param* _myVar2_ " _the value2_ "
