/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AccessTypeEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccessTypeEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Access"/>
 * &lt;enumeration value="Read"/>
 * &lt;enumeration value="Write"/>
 * &lt;enumeration value="ReadWrite"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("f516e112-a6c2-4843-8747-0df34a802784")
@XmlType(name = "AccessTypeEnum")
@XmlEnum
public enum AccessTypeEnum {
    @objid ("e616b6d9-cd25-443f-8824-c18610c8a6e4")
    @XmlEnumValue("Access")
    ACCESS("Access"),
    @objid ("b2145a9e-b5ce-4221-b257-abecfe0c4d69")
    @XmlEnumValue("Read")
    READ("Read"),
    @objid ("42ddbd02-a6fc-4625-8f48-b2f551f38d29")
    @XmlEnumValue("Write")
    WRITE("Write"),
    @objid ("256a4ab2-45e6-4d09-b093-3959696226d4")
    @XmlEnumValue("ReadWrite")
    READ_WRITE("ReadWrite");

    @objid ("bed660ee-1a2c-4a17-a53a-1c885068fc69")
    private final String value;

    @objid ("e7e6f539-ce76-4939-9425-9509935d6b08")
    AccessTypeEnum(String v) {
        value = v;
    }

    @objid ("5a32ebb4-4da7-46d2-a10c-f459bec2d533")
    public String value() {
        return value;
    }

    @objid ("45ef4d14-5a10-46d5-9a10-37c86ab4cdfb")
    public static AccessTypeEnum fromValue(String v) {
        for (AccessTypeEnum c: AccessTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
