/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Access complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Access">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}RelationshipType">
 * &lt;attribute name="accessType" type="{http://www.opengroup.org/xsd/archimate/3.0/}AccessTypeEnum" default="Access" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("a0cf513e-72e1-4653-bb0f-8c6a5a19858b")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Access")
public class Access extends RelationshipType {
    @objid ("36a1fd00-074c-4f26-b8cf-d97df0505bbb")
    @XmlAttribute(name = "accessType")
    protected AccessTypeEnum accessType;

    /**
     * Gets the value of the accessType property.
     *
     * @return possible object is
     * {@link AccessTypeEnum }
     */
    @objid ("d96659ef-e9cf-42b4-898a-34925dc0fa84")
    public AccessTypeEnum getAccessType() {
        if (accessType == null) {
            return AccessTypeEnum.ACCESS;
        } else {
            return accessType;
        }

    }

    /**
     * Sets the value of the accessType property.
     *
     * @param value allowed object is
     * {@link AccessTypeEnum }
     */
    @objid ("e3978854-f632-4821-975b-0ce159115109")
    public void setAccessType(AccessTypeEnum value) {
        this.accessType = value;
    }

}
