/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for CompositeTypeEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompositeTypeEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Grouping"/>
 * &lt;enumeration value="Location"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("0e72d0a2-0a0e-4c5c-ab49-d471df16203e")
@XmlType(name = "CompositeTypeEnum")
@XmlEnum
public enum CompositeTypeEnum {
    @objid ("3cf676ec-2da4-4636-a7ca-fc528b3c5111")
    @XmlEnumValue("Grouping")
    GROUPING("Grouping"),
    @objid ("9f725305-79b9-4060-b948-05db87bd0571")
    @XmlEnumValue("Location")
    LOCATION("Location");

    @objid ("3432defd-19d5-4044-85d5-c40dd2958436")
    private final String value;

    @objid ("33aeae28-10a0-4991-ae03-da102432830a")
    CompositeTypeEnum(String v) {
        value = v;
    }

    @objid ("c4014f38-01f7-4413-a6d3-833046a81750")
    public String value() {
        return value;
    }

    @objid ("cbc39e49-18d3-4917-9166-c978105288c4")
    public static CompositeTypeEnum fromValue(String v) {
        for (CompositeTypeEnum c: CompositeTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
