/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Graphical connection type.
 *
 * If the 'relationshipRef' attribute is present, the connection should reference an existing ArchiMate relationship.
 *
 * If the connection is an ArchiMate relationship type, the connection's label, documentation and properties may be determined
 * (i.e inherited) from those in the referenced ArchiMate relationship. Otherwise the connection's label, documentation and properties
 * can be provided and will be additional to (or over-ride) those contained in the referenced ArchiMate relationship.
 *
 *
 * <p>Java class for ConnectionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConnectionType">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}ViewConceptType">
 * &lt;sequence>
 * &lt;element name="sourceAttachment" type="{http://www.opengroup.org/xsd/archimate/3.0/}LocationType" minOccurs="0"/>
 * &lt;element name="bendpoint" type="{http://www.opengroup.org/xsd/archimate/3.0/}LocationType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="targetAttachment" type="{http://www.opengroup.org/xsd/archimate/3.0/}LocationType" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("688d6925-797e-450f-8a37-f04f0c9370fa")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionType", propOrder = {
    "sourceAttachment",
    "bendpoint",
    "targetAttachment"
})
@XmlSeeAlso({
    Line.class,
    SourcedConnectionType.class
})
public abstract class ConnectionType extends ViewConceptType {
    @objid ("a5f5639a-af60-4434-8aad-8f4504ba52c1")
    protected LocationType sourceAttachment;

    @objid ("e23a3c9d-86d6-4675-9853-51c6d1ea65e6")
    protected List<LocationType> bendpoint;

    @objid ("dbc05995-7dab-46f5-9706-7f7f9c945677")
    protected LocationType targetAttachment;

    @objid ("1bcd2666-7de1-4de5-935c-d961d806987e")
    @XmlAttribute(name = "source")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object source;

    @objid ("d4f682a9-6531-438a-a386-a4e0d5c5cf71")
    @XmlAttribute(name = "target")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object target;

    /**
     * Gets the value of the sourceAttachment property.
     *
     * @return possible object is
     * {@link LocationType }
     */
    @objid ("08690c7c-94b3-4f95-b22d-24dbdca8f182")
    public LocationType getSourceAttachment() {
        return sourceAttachment;
    }

    /**
     * Sets the value of the sourceAttachment property.
     *
     * @param value allowed object is
     * {@link LocationType }
     */
    @objid ("08b31ffd-5da7-4a7a-addd-a789dab7b25a")
    public void setSourceAttachment(LocationType value) {
        this.sourceAttachment = value;
    }

    /**
     * Gets the value of the bendpoint property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bendpoint property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getBendpoint().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     */
    @objid ("8ab9a9b7-ad97-4fc4-ae92-9c89650651ac")
    public List<LocationType> getBendpoint() {
        if (bendpoint == null) {
            bendpoint = new ArrayList<LocationType>();
        }
        return this.bendpoint;
    }

    /**
     * Gets the value of the targetAttachment property.
     *
     * @return possible object is
     * {@link LocationType }
     */
    @objid ("fa20a378-fdd3-4d5b-bf9d-286d3827f002")
    public LocationType getTargetAttachment() {
        return targetAttachment;
    }

    /**
     * Sets the value of the targetAttachment property.
     *
     * @param value allowed object is
     * {@link LocationType }
     */
    @objid ("510752c9-ebc5-4624-acb6-8204198a9998")
    public void setTargetAttachment(LocationType value) {
        this.targetAttachment = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("1f963323-bd5d-4732-81cb-b8d2da1216d7")
    public Object getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("d6f922f7-a9b6-4cdb-9ba0-dbd9c604f261")
    public void setSource(Object value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("b84d45d4-a05b-4649-9e15-4b543ba70385")
    public Object getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("3cc87840-425a-4878-84df-5e0e42c8e31f")
    public void setTarget(Object value) {
        this.target = value;
    }

}
