/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for DataType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataType">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="string"/>
 * &lt;enumeration value="boolean"/>
 * &lt;enumeration value="currency"/>
 * &lt;enumeration value="date"/>
 * &lt;enumeration value="time"/>
 * &lt;enumeration value="number"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("bfc10a9f-e31f-454d-8fd9-6305a8a976aa")
@XmlType(name = "DataType")
@XmlEnum
public enum DataType {
    @objid ("334838bc-9683-401d-b093-d633b15fef25")
    @XmlEnumValue("string")
    STRING("string"),
    @objid ("24e54f22-2660-4006-83f1-d0a861d2e3fc")
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @objid ("6cd84db8-8e3f-4ca4-a907-bf527b8069f4")
    @XmlEnumValue("currency")
    CURRENCY("currency"),
    @objid ("2c0beb19-41dd-47bf-a137-f1dfef17f6c0")
    @XmlEnumValue("date")
    DATE("date"),
    @objid ("ee068d40-2ab3-487e-a237-15d2b10d0be4")
    @XmlEnumValue("time")
    TIME("time"),
    @objid ("0e0b5be1-67be-4108-8d3a-cb3bb62163dd")
    @XmlEnumValue("number")
    NUMBER("number");

    @objid ("1eeb4549-e090-4bba-8894-5a038736488f")
    private final String value;

    @objid ("a6851756-f571-4b4a-957c-6c5091a481a1")
    DataType(String v) {
        value = v;
    }

    @objid ("e276c81d-7469-4735-bdb9-141aec47d471")
    public String value() {
        return value;
    }

    @objid ("0792d921-081c-439b-b01e-887dced8d517")
    public static DataType fromValue(String v) {
        for (DataType c: DataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
