/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Node type to allow an Element in a Artifact.
 *
 * The node's label, documentation and properties may be determined
 * (i.e inherited) from those in the referenced ArchiMate element. Otherwise the node's label, documentation and properties
 * can be provided and will be additional to (or over-ride) those contained in the referenced ArchiMate element.
 *
 *
 * <p>Java class for Element complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Element">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}Container">
 * &lt;attribute name="elementRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("9693ee26-737e-431b-9602-1f75fca6764e")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element")
public class Element extends Container {
    @objid ("79dc85d9-2e86-40d5-b7e3-b14adb489986")
    @XmlAttribute(name = "elementRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object elementRef;

    /**
     * Gets the value of the elementRef property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("ead9d8e2-6fa1-4c4d-aa93-73648aae8124")
    public Object getElementRef() {
        return elementRef;
    }

    /**
     * Sets the value of the elementRef property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("cc874176-a24c-4bdb-b5ed-899f15b8f3c8")
    public void setElementRef(Object value) {
        this.elementRef = value;
    }

}
