/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ElementTypeEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ElementTypeEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="BusinessActor"/>
 * &lt;enumeration value="BusinessRole"/>
 * &lt;enumeration value="BusinessCollaboration"/>
 * &lt;enumeration value="BusinessInterface"/>
 * &lt;enumeration value="BusinessProcess"/>
 * &lt;enumeration value="BusinessFunction"/>
 * &lt;enumeration value="BusinessInteraction"/>
 * &lt;enumeration value="BusinessEvent"/>
 * &lt;enumeration value="BusinessService"/>
 * &lt;enumeration value="BusinessObject"/>
 * &lt;enumeration value="Contract"/>
 * &lt;enumeration value="Representation"/>
 * &lt;enumeration value="Product"/>
 * &lt;enumeration value="ApplicationComponent"/>
 * &lt;enumeration value="ApplicationCollaboration"/>
 * &lt;enumeration value="ApplicationInterface"/>
 * &lt;enumeration value="ApplicationFunction"/>
 * &lt;enumeration value="ApplicationInteraction"/>
 * &lt;enumeration value="ApplicationProcess"/>
 * &lt;enumeration value="ApplicationEvent"/>
 * &lt;enumeration value="ApplicationService"/>
 * &lt;enumeration value="DataObject"/>
 * &lt;enumeration value="Node"/>
 * &lt;enumeration value="Device"/>
 * &lt;enumeration value="SystemSoftware"/>
 * &lt;enumeration value="TechnologyCollaboration"/>
 * &lt;enumeration value="TechnologyInterface"/>
 * &lt;enumeration value="Path"/>
 * &lt;enumeration value="CommunicationNetwork"/>
 * &lt;enumeration value="TechnologyFunction"/>
 * &lt;enumeration value="TechnologyProcess"/>
 * &lt;enumeration value="TechnologyInteraction"/>
 * &lt;enumeration value="TechnologyEvent"/>
 * &lt;enumeration value="TechnologyService"/>
 * &lt;enumeration value="Artifact"/>
 * &lt;enumeration value="Equipment"/>
 * &lt;enumeration value="Facility"/>
 * &lt;enumeration value="DistributionNetwork"/>
 * &lt;enumeration value="Material"/>
 * &lt;enumeration value="Stakeholder"/>
 * &lt;enumeration value="Driver"/>
 * &lt;enumeration value="Assessment"/>
 * &lt;enumeration value="Goal"/>
 * &lt;enumeration value="Outcome"/>
 * &lt;enumeration value="Principle"/>
 * &lt;enumeration value="Requirement"/>
 * &lt;enumeration value="Constraint"/>
 * &lt;enumeration value="Meaning"/>
 * &lt;enumeration value="Value"/>
 * &lt;enumeration value="Resource"/>
 * &lt;enumeration value="Capability"/>
 * &lt;enumeration value="CourseOfAction"/>
 * &lt;enumeration value="WorkPackage"/>
 * &lt;enumeration value="Deliverable"/>
 * &lt;enumeration value="ImplementationEvent"/>
 * &lt;enumeration value="Plateau"/>
 * &lt;enumeration value="Gap"/>
 * &lt;enumeration value="Grouping"/>
 * &lt;enumeration value="Location"/>
 * &lt;enumeration value="AndJunction"/>
 * &lt;enumeration value="OrJunction"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("2d300a89-5a48-4b8d-9845-af8e5bb77d9c")
@XmlType(name = "ElementTypeEnum")
@XmlEnum
public enum ElementTypeEnum {
    @objid ("063ddfde-c77e-4f73-8c14-976736ec0438")
    @XmlEnumValue("BusinessActor")
    BUSINESS_ACTOR("BusinessActor"),
    @objid ("f3832180-be96-42df-b727-93afa57fdcce")
    @XmlEnumValue("BusinessRole")
    BUSINESS_ROLE("BusinessRole"),
    @objid ("cba2c8e6-0a3c-4406-81ec-6a73f0f662b8")
    @XmlEnumValue("BusinessCollaboration")
    BUSINESS_COLLABORATION("BusinessCollaboration"),
    @objid ("2390ad9a-8dbe-4c4d-9bc5-c22f9c374e89")
    @XmlEnumValue("BusinessInterface")
    BUSINESS_INTERFACE("BusinessInterface"),
    @objid ("ad7f183c-9244-4a6b-ba29-e30e5e9fe2ce")
    @XmlEnumValue("BusinessProcess")
    BUSINESS_PROCESS("BusinessProcess"),
    @objid ("0c72689b-f462-4ac2-9e01-636f198b7dfb")
    @XmlEnumValue("BusinessFunction")
    BUSINESS_FUNCTION("BusinessFunction"),
    @objid ("53c08b1d-f5a9-43ba-a0fc-b81434e76a8a")
    @XmlEnumValue("BusinessInteraction")
    BUSINESS_INTERACTION("BusinessInteraction"),
    @objid ("623757f1-e6a5-4983-bec9-15db4c14f3c1")
    @XmlEnumValue("BusinessEvent")
    BUSINESS_EVENT("BusinessEvent"),
    @objid ("6c006c45-991d-4f38-9947-fda3da68449a")
    @XmlEnumValue("BusinessService")
    BUSINESS_SERVICE("BusinessService"),
    @objid ("39ff8dd8-fa2b-4655-b802-7b5e86a72a36")
    @XmlEnumValue("BusinessObject")
    BUSINESS_OBJECT("BusinessObject"),
    @objid ("84100893-4d00-4a77-9cfb-afc0a9b9ba0b")
    @XmlEnumValue("Contract")
    CONTRACT("Contract"),
    @objid ("19eaf6d6-c6e1-4ebd-920d-2e66358f379d")
    @XmlEnumValue("Representation")
    REPRESENTATION("Representation"),
    @objid ("a4892abd-8c74-45f7-9751-7e56e75277df")
    @XmlEnumValue("Product")
    PRODUCT("Product"),
    @objid ("a2094c8b-011d-406d-bb42-4ae55e5b9602")
    @XmlEnumValue("ApplicationComponent")
    APPLICATION_COMPONENT("ApplicationComponent"),
    @objid ("48b7ef12-de73-4525-a1c4-b32be4ab8c93")
    @XmlEnumValue("ApplicationCollaboration")
    APPLICATION_COLLABORATION("ApplicationCollaboration"),
    @objid ("11ff9e9c-6d38-43a8-95fc-7a6caaa46a8f")
    @XmlEnumValue("ApplicationInterface")
    APPLICATION_INTERFACE("ApplicationInterface"),
    @objid ("2e4d1b9b-2002-4394-ab05-e19a1094be8c")
    @XmlEnumValue("ApplicationFunction")
    APPLICATION_FUNCTION("ApplicationFunction"),
    @objid ("3088f374-f5c0-4513-9bbb-87acb9643501")
    @XmlEnumValue("ApplicationInteraction")
    APPLICATION_INTERACTION("ApplicationInteraction"),
    @objid ("7811c9a4-58aa-47f4-94b8-09944f02bfb4")
    @XmlEnumValue("ApplicationProcess")
    APPLICATION_PROCESS("ApplicationProcess"),
    @objid ("394bc2fa-5b51-45f6-ae48-78cd1aa35459")
    @XmlEnumValue("ApplicationEvent")
    APPLICATION_EVENT("ApplicationEvent"),
    @objid ("263c1b7d-30e1-408b-a6a0-22c223277f10")
    @XmlEnumValue("ApplicationService")
    APPLICATION_SERVICE("ApplicationService"),
    @objid ("c94d71d0-4133-4954-8b72-dc644c9747a6")
    @XmlEnumValue("DataObject")
    DATA_OBJECT("DataObject"),
    @objid ("4bf335d6-52f5-4f57-bb6d-11860e74e1e4")
    @XmlEnumValue("Node")
    NODE("Node"),
    @objid ("a209b97f-14a0-43ad-b81e-5021f5e80cd3")
    @XmlEnumValue("Device")
    DEVICE("Device"),
    @objid ("786b3cfa-caba-43e0-a5b9-e141ecd505e1")
    @XmlEnumValue("SystemSoftware")
    SYSTEM_SOFTWARE("SystemSoftware"),
    @objid ("10d404cb-a6f6-4df8-b2cf-405cb847167e")
    @XmlEnumValue("TechnologyCollaboration")
    TECHNOLOGY_COLLABORATION("TechnologyCollaboration"),
    @objid ("e56befc5-6fe3-4feb-bad2-bcb758674d96")
    @XmlEnumValue("TechnologyInterface")
    TECHNOLOGY_INTERFACE("TechnologyInterface"),
    @objid ("19c07155-f3f3-4ed7-9236-a70d19bcc2d8")
    @XmlEnumValue("Path")
    PATH("Path"),
    @objid ("1369bc39-c04d-462b-8f96-f1e8a79f0a23")
    @XmlEnumValue("CommunicationNetwork")
    COMMUNICATION_NETWORK("CommunicationNetwork"),
    @objid ("3e8a00b5-5e3f-4d5d-90f1-92d77befb2a1")
    @XmlEnumValue("TechnologyFunction")
    TECHNOLOGY_FUNCTION("TechnologyFunction"),
    @objid ("590f08c1-2d2f-4b2b-9a09-94358e5c41a4")
    @XmlEnumValue("TechnologyProcess")
    TECHNOLOGY_PROCESS("TechnologyProcess"),
    @objid ("c4728d18-f9f0-4791-aa5f-efbdcaeabce7")
    @XmlEnumValue("TechnologyInteraction")
    TECHNOLOGY_INTERACTION("TechnologyInteraction"),
    @objid ("5cf8476c-4592-424b-afb4-89e0749f4965")
    @XmlEnumValue("TechnologyEvent")
    TECHNOLOGY_EVENT("TechnologyEvent"),
    @objid ("8905c2e4-9f4f-4100-989f-28bcf5557407")
    @XmlEnumValue("TechnologyService")
    TECHNOLOGY_SERVICE("TechnologyService"),
    @objid ("831a111c-7593-4ea0-acf8-73588adbee6d")
    @XmlEnumValue("Artifact")
    ARTIFACT("Artifact"),
    @objid ("1270583d-d9aa-4cdb-a742-f9475c030abc")
    @XmlEnumValue("Equipment")
    EQUIPMENT("Equipment"),
    @objid ("5fbdcc8c-ae0b-4d35-8712-3c6830a48914")
    @XmlEnumValue("Facility")
    FACILITY("Facility"),
    @objid ("543fe8b4-11b0-4d2a-bc49-944c24ecae53")
    @XmlEnumValue("DistributionNetwork")
    DISTRIBUTION_NETWORK("DistributionNetwork"),
    @objid ("b0e18a64-f2d1-4f45-83f0-aadfe919cbbf")
    @XmlEnumValue("Material")
    MATERIAL("Material"),
    @objid ("688e955a-bdd9-4b41-92b4-d7597010af17")
    @XmlEnumValue("Stakeholder")
    STAKEHOLDER("Stakeholder"),
    @objid ("bd7d0e0b-a984-4fdc-a7a9-d0cc4d6e1347")
    @XmlEnumValue("Driver")
    DRIVER("Driver"),
    @objid ("1be46761-57a1-4d7c-85bc-c0af803690a0")
    @XmlEnumValue("Assessment")
    ASSESSMENT("Assessment"),
    @objid ("af39bc1d-aa18-4c86-9d7c-b4607fa15e76")
    @XmlEnumValue("Goal")
    GOAL("Goal"),
    @objid ("70e47510-e1c3-442c-9082-fbf643e34297")
    @XmlEnumValue("Outcome")
    OUTCOME("Outcome"),
    @objid ("454dc6c0-22b7-4481-9322-5d6fdb91b3d0")
    @XmlEnumValue("Principle")
    PRINCIPLE("Principle"),
    @objid ("9f258611-a9ab-477d-8d68-0faf696180c9")
    @XmlEnumValue("Requirement")
    REQUIREMENT("Requirement"),
    @objid ("92cedc58-1435-4487-812c-9c495b1fcd68")
    @XmlEnumValue("Constraint")
    CONSTRAINT("Constraint"),
    @objid ("f2c9c579-15dc-4f9b-b911-c4366b2a0137")
    @XmlEnumValue("Meaning")
    MEANING("Meaning"),
    @objid ("14cf72e7-45f0-4732-9ec5-1befab3e9dc0")
    @XmlEnumValue("Value")
    VALUE("Value"),
    @objid ("0fd98f12-b9a5-4974-a18c-56f668c26949")
    @XmlEnumValue("Resource")
    RESOURCE("Resource"),
    @objid ("8063dafd-7c0a-4fa8-90e6-8fabaac135ea")
    @XmlEnumValue("Capability")
    CAPABILITY("Capability"),
    @objid ("607a5f54-d925-4ad7-981c-5b85cdb99abf")
    @XmlEnumValue("CourseOfAction")
    COURSE_OF_ACTION("CourseOfAction"),
    @objid ("d84419fc-0897-4ab0-8791-b4a6a5b609de")
    @XmlEnumValue("WorkPackage")
    WORK_PACKAGE("WorkPackage"),
    @objid ("bfdb5903-030c-4dda-bf8b-b68a423ff6fb")
    @XmlEnumValue("Deliverable")
    DELIVERABLE("Deliverable"),
    @objid ("c368af0b-ba5f-4cb4-982f-84eb75059383")
    @XmlEnumValue("ImplementationEvent")
    IMPLEMENTATION_EVENT("ImplementationEvent"),
    @objid ("abde178c-cdfe-46e7-b430-b04514108d91")
    @XmlEnumValue("Plateau")
    PLATEAU("Plateau"),
    @objid ("ce4b784e-4c35-4fb3-8b9a-26f76108d39d")
    @XmlEnumValue("Gap")
    GAP("Gap"),
    @objid ("3affbd43-0aa5-4f27-a499-ed58ea042a20")
    @XmlEnumValue("Grouping")
    GROUPING("Grouping"),
    @objid ("c81ffa17-fa27-48f0-87cb-72560904ed52")
    @XmlEnumValue("Location")
    LOCATION("Location"),
    @objid ("c2d85e69-93f0-4ad5-a484-e26b2cbd60f5")
    @XmlEnumValue("AndJunction")
    AND_JUNCTION("AndJunction"),
    @objid ("95782a7a-a6e9-4d0c-bb56-b0713173c95c")
    @XmlEnumValue("OrJunction")
    OR_JUNCTION("OrJunction");

    @objid ("c2865fe6-218e-4bf2-b21e-6ad37423c0aa")
    private final String value;

    @objid ("f78713e4-306b-4db9-bf26-a3dd4486d00b")
    ElementTypeEnum(String v) {
        value = v;
    }

    @objid ("b37651aa-ccd8-4a1f-9294-9c2fd2be5c5e")
    public String value() {
        return value;
    }

    @objid ("3316b51f-3d42-40d9-a070-c81d323342c6")
    public static ElementTypeEnum fromValue(String v) {
        for (ElementTypeEnum c: ElementTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
