/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for FontStyleEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FontStyleEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="plain"/>
 * &lt;enumeration value="bold"/>
 * &lt;enumeration value="italic"/>
 * &lt;enumeration value="underline"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("6e903563-a9a4-42f8-8810-90d5ecc58477")
@XmlType(name = "FontStyleEnum")
@XmlEnum
public enum FontStyleEnum {
    @objid ("98a9c228-2d54-4886-aa14-8d024ae91f2d")
    @XmlEnumValue("plain")
    PLAIN("plain"),
    @objid ("d4032c3d-423b-413f-b687-3da66b9f3fb7")
    @XmlEnumValue("bold")
    BOLD("bold"),
    @objid ("093e79aa-8bc7-47f2-8428-26cb94b7b7ca")
    @XmlEnumValue("italic")
    ITALIC("italic"),
    @objid ("20f79345-5ab4-46c4-b2fa-eb158638cde6")
    @XmlEnumValue("underline")
    UNDERLINE("underline");

    @objid ("537a5c37-f4d6-4975-923a-f10c134de6d6")
    private final String value;

    @objid ("34856cea-48b9-4dc3-a6a5-382dc5ea0267")
    FontStyleEnum(String v) {
        value = v;
    }

    @objid ("b3e4a4a1-9d9f-4f7e-a574-8fa72e77b102")
    public String value() {
        return value;
    }

    @objid ("abfb2707-0d8c-4a60-b489-8c903d57b9bf")
    public static FontStyleEnum fromValue(String v) {
        for (FontStyleEnum c: FontStyleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
