/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Font type.
 *
 *
 * <p>Java class for FontType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FontType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="color" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBColorType" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="size" type="{http://www.opengroup.org/xsd/archimate/3.0/}nonNegativeHalfGranularityDecimal" />
 * &lt;attribute name="style" type="{http://www.opengroup.org/xsd/archimate/3.0/}FontStyleType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("debe5fc7-b0ba-4cdd-abe5-f6ea36dd2cad")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FontType", propOrder = {
    "color"
})
public class FontType {
    @objid ("ff88e044-67b2-474c-aa88-ba670398dc30")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("8d0aa998-b73c-4b9d-aaaa-ea15082b1707")
    @XmlAttribute(name = "style")
    protected List<FontStyleEnum> style;

    @objid ("ff7c59bc-4484-49f8-bd2b-c7d97a43b188")
    protected RGBColorType color;

    @objid ("7a90caa7-999f-4d6d-b69e-98f87feb0823")
    @XmlAttribute(name = "size")
    protected BigDecimal size;

    /**
     * Gets the value of the color property.
     *
     * @return possible object is
     * {@link RGBColorType }
     */
    @objid ("5e33f1c6-f684-4423-b162-060982b596a7")
    public RGBColorType getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value allowed object is
     * {@link RGBColorType }
     */
    @objid ("120e2bc7-b0da-4d81-a793-11f5db5c788e")
    public void setColor(RGBColorType value) {
        this.color = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("767ea32f-05ec-4ca6-9b99-59aaefcf05d3")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("a8032c91-cfeb-4eb0-b70d-3c097b89a9cd")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the size property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    @objid ("93c67a05-d0d3-4f5c-a24a-d05c8d9012b3")
    public BigDecimal getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value allowed object is
     * {@link BigDecimal }
     */
    @objid ("af5b316d-0233-4dd7-80fa-f4c89e908328")
    public void setSize(BigDecimal value) {
        this.size = value;
    }

    /**
     * Gets the value of the style property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the style property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getStyle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FontStyleEnum }
     */
    @objid ("ac3b7bce-e6ca-4ba0-a186-3677b0430c35")
    public List<FontStyleEnum> getStyle() {
        if (style == null) {
            style = new ArrayList<FontStyleEnum>();
        }
        return this.style;
    }

}
