/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Node type to allow a Label in a Artifact. the "label" element holds the info for the Note.
 *
 *
 * <p>Java class for Label complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Label">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}ViewNodeType">
 * &lt;attribute name="conceptRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="xpathPart" type="{http://www.opengroup.org/xsd/archimate/3.0/}XPATH_2.0_Expression" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("db4117d3-5b8f-4a9c-9f98-a0c911f9832a")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Label")
public class Label extends ViewNodeType {
    @objid ("cbf418c4-1658-4dd5-a72c-557e45f0de9f")
    @XmlAttribute(name = "xpathPart")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xpathPart;

    @objid ("a0b1af12-ad8f-4b6e-a23a-097ce0347661")
    @XmlAttribute(name = "conceptRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object conceptRef;

    /**
     * Gets the value of the conceptRef property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("1a9fd363-faf1-475f-b508-59ba4d32df29")
    public Object getConceptRef() {
        return conceptRef;
    }

    /**
     * Sets the value of the conceptRef property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("5a6a5edb-1331-455e-a53e-c4d3d8c53bd3")
    public void setConceptRef(Object value) {
        this.conceptRef = value;
    }

    /**
     * Gets the value of the xpathPart property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("fdfea60e-9373-4e22-86f8-2e1a690267d7")
    public String getXpathPart() {
        return xpathPart;
    }

    /**
     * Sets the value of the xpathPart property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("ffb8730d-c34e-4751-9942-da1b578ec28b")
    public void setXpathPart(String value) {
        this.xpathPart = value;
    }

}
