/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * A base string type for multi-language strings.
 *
 *
 * <p>Java class for LangStringType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LangStringType">
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("bc849b01-cb57-4eb2-a48a-7386ae12dd38")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LangStringType", propOrder = {
    "value"
})
@XmlSeeAlso({
    PreservedLangStringType.class
})
public class LangStringType {
    @objid ("03c0e13d-57a1-47bc-ad20-c670cdf40724")
    @XmlValue
    protected String value;

    @objid ("134cbcb9-5e4d-48c1-a294-d626f368415c")
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("44f5837d-22e2-4920-a1ae-2eefdf553b8e")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("b626c925-b854-4d5e-a051-f2b06147ce72")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("b55621e3-347b-4247-9e30-f3b67f98ae7c")
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("591d1c69-0dc3-4ad3-938a-e084bcb053c8")
    public void setLang(String value) {
        this.lang = value;
    }

}
