/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * An instance of the meta-data element contains data structures that declare descriptive information
 * about a meta-data element's parent only.
 *
 * One or more different meta-data models may be declared as child extensions of a meta-data element.
 *
 *
 * <p>Java class for MetadataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MetadataType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;choice>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate/3.0/}SchemaInfoGroup"/>
 * &lt;element name="schemaInfo" type="{http://www.opengroup.org/xsd/archimate/3.0/}SchemaInfoType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/choice>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("17b1f1a7-3b37-4fad-835c-704aa191eef5")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetadataType", propOrder = {
    "schema",
    "schemaversion",
    "any",
    "schemaInfo"
})
public class MetadataType {
    @objid ("ac45903b-07e0-4cc0-bbc3-80604aed1db5")
    protected String schema;

    @objid ("6acfeba8-3c2e-4b5b-b594-5d5cf817a269")
    protected String schemaversion;

    @objid ("ea5ad053-db96-4532-8e20-7457269d264d")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @objid ("d3b59894-a597-41b4-a31a-b220237e2aa8")
    protected List<SchemaInfoType> schemaInfo;

    /**
     * Gets the value of the schema property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("160a10d0-72fa-494c-9ffd-4f83ed907580")
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("5437aea1-dfaa-47fc-926a-33c24e350621")
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the schemaversion property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("3369f242-62b0-4a6a-8e2c-d0b7f4c115d7")
    public String getSchemaversion() {
        return schemaversion;
    }

    /**
     * Sets the value of the schemaversion property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("966431be-2f24-47de-af6b-ab532a20b41d")
    public void setSchemaversion(String value) {
        this.schemaversion = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("f853f08f-acf7-4f58-9991-9d44dad9b544")
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the schemaInfo property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schemaInfo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getSchemaInfo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemaInfoType }
     */
    @objid ("b9a428e8-3b4e-41ab-a488-463b39c4e173")
    public List<SchemaInfoType> getSchemaInfo() {
        if (schemaInfo == null) {
            schemaInfo = new ArrayList<SchemaInfoType>();
        }
        return this.schemaInfo;
    }

}
