/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.modelio.archimate.exchange.v30.xmlmodel package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@objid ("19497816-b15e-4f27-b948-d83b416311f9")
@XmlRegistry
public class ObjectFactory {
    @objid ("44713a7d-98a8-4ac3-89af-02519d534700")
    private static final QName _Model_QNAME = new QName("http://www.opengroup.org/xsd/archimate/3.0/", "model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.modelio.archimate.exchange.v30.xmlmodel
     */
    @objid ("1b847f2e-9e90-4a8f-b22b-1c28c3da8bbf")
    public ObjectFactory() {

    }

    /**
     * Create an instance of {@link ModelType }
     */
    @objid ("350a41d5-6432-46fc-81e8-d38a992756f3")
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link TechnologyProcess }
     */
    @objid ("726dd693-d5ba-4443-8414-804ed67ceafa")
    public TechnologyProcess createTechnologyProcess() {
        return new TechnologyProcess();
    }

    /**
     * Create an instance of {@link PropertyDefinitionType }
     */
    @objid ("c0549e53-6f0f-47bf-a89c-324594fcb318")
    public PropertyDefinitionType createPropertyDefinitionType() {
        return new PropertyDefinitionType();
    }

    /**
     * Create an instance of {@link Node }
     */
    @objid ("67e68a1d-5bb9-4e8f-ab7a-2b75f67dd813")
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Access }
     */
    @objid ("921f1806-3b1a-4799-99b2-f0706f6e7471")
    public Access createAccess() {
        return new Access();
    }

    /**
     * Create an instance of {@link Product }
     */
    @objid ("13aab224-c9f4-4d7a-83c7-8f924ad0cdcf")
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link BusinessObject }
     */
    @objid ("5708646b-ffc7-4685-9b51-ffbaad0b1e95")
    public BusinessObject createBusinessObject() {
        return new BusinessObject();
    }

    /**
     * Create an instance of {@link ReferenceType }
     */
    @objid ("4f8b75aa-90fa-4db9-a5d8-79e61ece44da")
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link BusinessCollaboration }
     */
    @objid ("135f1cc6-ec1a-4076-88f8-96d07bac5d3a")
    public BusinessCollaboration createBusinessCollaboration() {
        return new BusinessCollaboration();
    }

    /**
     * Create an instance of {@link Assignment }
     */
    @objid ("bc1fbe14-3e21-4e50-be53-7639c9b354c2")
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link Goal }
     */
    @objid ("1bf60251-8af1-4bbb-9730-4fd711daf429")
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link ViewsType }
     */
    @objid ("cf2ea09f-47da-436e-ba3b-aca98d41705b")
    public ViewsType createViewsType() {
        return new ViewsType();
    }

    /**
     * Create an instance of {@link ConcernType }
     */
    @objid ("41b89931-1000-4946-8b6b-27aa6190690c")
    public ConcernType createConcernType() {
        return new ConcernType();
    }

    /**
     * Create an instance of {@link ImplementationEvent }
     */
    @objid ("cbb6bfeb-f0f7-484f-97a0-13a6eca53a77")
    public ImplementationEvent createImplementationEvent() {
        return new ImplementationEvent();
    }

    /**
     * Create an instance of {@link StakeholderType }
     */
    @objid ("9ed24956-126e-40ed-b1eb-afc86075ebf7")
    public StakeholderType createStakeholderType() {
        return new StakeholderType();
    }

    /**
     * Create an instance of {@link AndJunction }
     */
    @objid ("ac9fad45-4b1d-4fa6-b3f7-ae3d7fb3758e")
    public AndJunction createAndJunction() {
        return new AndJunction();
    }

    /**
     * Create an instance of {@link DiagramsType }
     */
    @objid ("27eab29e-5374-4ca3-bf43-cd010d88aa60")
    public DiagramsType createDiagramsType() {
        return new DiagramsType();
    }

    /**
     * Create an instance of {@link Capability }
     */
    @objid ("ed99fe89-d68d-40ba-8b9d-f924e41f25b8")
    public Capability createCapability() {
        return new Capability();
    }

    /**
     * Create an instance of {@link BusinessEvent }
     */
    @objid ("72d5087e-075d-4d05-ad43-6d56da45bce1")
    public BusinessEvent createBusinessEvent() {
        return new BusinessEvent();
    }

    /**
     * Create an instance of {@link DistributionNetwork }
     */
    @objid ("6365d471-0551-44dd-b544-626cd624d200")
    public DistributionNetwork createDistributionNetwork() {
        return new DistributionNetwork();
    }

    /**
     * Create an instance of {@link ApplicationFunction }
     */
    @objid ("369c7e8c-cbd9-467f-b83d-1558b7da2660")
    public ApplicationFunction createApplicationFunction() {
        return new ApplicationFunction();
    }

    /**
     * Create an instance of {@link TechnologyInterface }
     */
    @objid ("6b4a368b-8dc5-4a1a-9813-edb9947337d9")
    public TechnologyInterface createTechnologyInterface() {
        return new TechnologyInterface();
    }

    /**
     * Create an instance of {@link ApplicationEvent }
     */
    @objid ("a273cda1-21de-4d0a-bf73-551361909290")
    public ApplicationEvent createApplicationEvent() {
        return new ApplicationEvent();
    }

    /**
     * Create an instance of {@link Grouping }
     */
    @objid ("153f8bc7-37b6-451b-bbbf-8f767a6acefb")
    public Grouping createGrouping() {
        return new Grouping();
    }

    /**
     * Create an instance of {@link Principle }
     */
    @objid ("1cf9a626-6915-4a13-8078-8153c4d9f99a")
    public Principle createPrinciple() {
        return new Principle();
    }

    /**
     * Create an instance of {@link AllowedRelationshipTypeType }
     */
    @objid ("490f21d7-62b7-4f62-a426-3890b553da62")
    public AllowedRelationshipTypeType createAllowedRelationshipTypeType() {
        return new AllowedRelationshipTypeType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     */
    @objid ("2236b25b-19ee-428c-8bc4-19475f3d0be2")
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link Line }
     */
    @objid ("0deb2c45-1488-4418-b30a-5c082e4589fa")
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Requirement }
     */
    @objid ("f3c07410-21a0-45ec-96f2-bf54b1f018dc")
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link Influence }
     */
    @objid ("f00fbf4d-955b-4ee2-8613-01f02a96ffcc")
    public Influence createInfluence() {
        return new Influence();
    }

    /**
     * Create an instance of {@link Contract }
     */
    @objid ("e528fcf0-38bd-4a07-99d6-d1ab1df2b68c")
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link ApplicationService }
     */
    @objid ("31460315-fb56-4da1-bdeb-cb419214d166")
    public ApplicationService createApplicationService() {
        return new ApplicationService();
    }

    /**
     * Create an instance of {@link Deliverable }
     */
    @objid ("95b4b14d-f18a-4b5c-bbff-ef6da7dfcdb1")
    public Deliverable createDeliverable() {
        return new Deliverable();
    }

    /**
     * Create an instance of {@link CommunicationNetwork }
     */
    @objid ("fbc54f76-5e83-4688-ac0b-e7045057024e")
    public CommunicationNetwork createCommunicationNetwork() {
        return new CommunicationNetwork();
    }

    /**
     * Create an instance of {@link ViewpointType }
     */
    @objid ("3f7266be-cb01-4e70-87e2-7cd0a5fbe2d2")
    public ViewpointType createViewpointType() {
        return new ViewpointType();
    }

    /**
     * Create an instance of {@link TechnologyCollaboration }
     */
    @objid ("bf9472f5-438b-4cd1-a377-0dff9e7ae473")
    public TechnologyCollaboration createTechnologyCollaboration() {
        return new TechnologyCollaboration();
    }

    /**
     * Create an instance of {@link ApplicationCollaboration }
     */
    @objid ("bd24031b-687f-437e-9af6-0e720bf98df7")
    public ApplicationCollaboration createApplicationCollaboration() {
        return new ApplicationCollaboration();
    }

    /**
     * Create an instance of {@link SchemaInfoType }
     */
    @objid ("293b1365-ea2a-487d-98dc-0027d2e33ce9")
    public SchemaInfoType createSchemaInfoType() {
        return new SchemaInfoType();
    }

    /**
     * Create an instance of {@link Aggregation }
     */
    @objid ("c6c665c5-a8ab-47ad-90ca-808ae10d50fd")
    public Aggregation createAggregation() {
        return new Aggregation();
    }

    /**
     * Create an instance of {@link PropertiesType }
     */
    @objid ("5a91aa5e-9f37-462d-8982-29ff28dd3174")
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link Specialization }
     */
    @objid ("75bc669b-d834-4dd7-88c5-a9ce49ca5901")
    public Specialization createSpecialization() {
        return new Specialization();
    }

    /**
     * Create an instance of {@link Association }
     */
    @objid ("dc381887-d0b1-425f-a24e-a35538cc8c52")
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link ElementsType }
     */
    @objid ("9bcbf92c-06b3-4330-b9ed-ff70762aa446")
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link Triggering }
     */
    @objid ("1bf6813f-bf57-4556-99d6-177a415ea140")
    public Triggering createTriggering() {
        return new Triggering();
    }

    /**
     * Create an instance of {@link Path }
     */
    @objid ("91346caf-a2de-45ff-b8a3-fb4a0869b517")
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link Plateau }
     */
    @objid ("1db6c6db-f132-4ee6-a27b-a5aea91da7d1")
    public Plateau createPlateau() {
        return new Plateau();
    }

    /**
     * Create an instance of {@link ApplicationComponent }
     */
    @objid ("d44abaa7-7cd1-49fe-9fe8-e971be368c5e")
    public ApplicationComponent createApplicationComponent() {
        return new ApplicationComponent();
    }

    /**
     * Create an instance of {@link StyleType }
     */
    @objid ("dbebe080-bc4d-4e5c-9ab6-7f7b1d50c054")
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link TechnologyInteraction }
     */
    @objid ("f4160ff1-e9fd-4b66-87ef-92b3155a782c")
    public TechnologyInteraction createTechnologyInteraction() {
        return new TechnologyInteraction();
    }

    /**
     * Create an instance of {@link ViewpointsType }
     */
    @objid ("f8b34f28-71e5-4b67-a4e1-920b15a48f47")
    public ViewpointsType createViewpointsType() {
        return new ViewpointsType();
    }

    /**
     * Create an instance of {@link Artifact }
     */
    @objid ("44603954-392d-4aed-af98-268eb70994de")
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link BusinessFunction }
     */
    @objid ("37031733-789a-4972-b42f-7ab3f4dc81cf")
    public BusinessFunction createBusinessFunction() {
        return new BusinessFunction();
    }

    /**
     * Create an instance of {@link Flow }
     */
    @objid ("eef05b36-b0ef-4914-8b7e-4636ab5aaa3e")
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link Diagram }
     */
    @objid ("b3087278-d921-4ec7-ae5e-37b5a2deed55")
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link Outcome }
     */
    @objid ("11776b0c-e638-453a-8f48-9a19dd53bb58")
    public Outcome createOutcome() {
        return new Outcome();
    }

    /**
     * Create an instance of {@link Relationship }
     */
    @objid ("5b856cef-b3e9-49a9-a717-a584864cff0a")
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Facility }
     */
    @objid ("b5a7d81b-b43a-45fa-9b30-94877b75cd2d")
    public Facility createFacility() {
        return new Facility();
    }

    /**
     * Create an instance of {@link LangStringType }
     */
    @objid ("c47bdd7f-4121-4986-94b6-24dd6e27c23d")
    public LangStringType createLangStringType() {
        return new LangStringType();
    }

    /**
     * Create an instance of {@link Constraint }
     */
    @objid ("252e0da5-621d-48f4-89c0-2dcb2b867f4b")
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link Label }
     */
    @objid ("ca4312d9-00ee-46e9-901f-3b957c664b58")
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link BusinessActor }
     */
    @objid ("eff11bd6-409c-4970-9536-60cd696b1c11")
    public BusinessActor createBusinessActor() {
        return new BusinessActor();
    }

    /**
     * Create an instance of {@link PropertyType }
     */
    @objid ("00c81653-9da1-42bf-8c11-b440fda61ec8")
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link StakeholdersType }
     */
    @objid ("00d7baf6-eb66-41f9-b1c7-9b9810727392")
    public StakeholdersType createStakeholdersType() {
        return new StakeholdersType();
    }

    /**
     * Create an instance of {@link BusinessInteraction }
     */
    @objid ("0cb64d92-3423-4268-b77e-e72364807053")
    public BusinessInteraction createBusinessInteraction() {
        return new BusinessInteraction();
    }

    /**
     * Create an instance of {@link WorkPackage }
     */
    @objid ("72134f92-ca34-42da-9a25-879468baada8")
    public WorkPackage createWorkPackage() {
        return new WorkPackage();
    }

    /**
     * Create an instance of {@link Serving }
     */
    @objid ("2b2142f3-bd85-4256-8994-d5cd799e462e")
    public Serving createServing() {
        return new Serving();
    }

    /**
     * Create an instance of {@link TechnologyFunction }
     */
    @objid ("6ba91adb-246d-43ec-8d85-b4cdad78a7f0")
    public TechnologyFunction createTechnologyFunction() {
        return new TechnologyFunction();
    }

    /**
     * Create an instance of {@link Container }
     */
    @objid ("4987f1b4-110f-48a9-ae75-788cd6397671")
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Stakeholder }
     */
    @objid ("59c1e361-57dd-4ec5-9ac8-704f2b53f974")
    public Stakeholder createStakeholder() {
        return new Stakeholder();
    }

    /**
     * Create an instance of {@link Device }
     */
    @objid ("87477ff0-a441-4ad9-b1f0-ae0ec5551153")
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link OrJunction }
     */
    @objid ("1cb43885-89fd-4bb3-9f76-bf01a5295946")
    public OrJunction createOrJunction() {
        return new OrJunction();
    }

    /**
     * Create an instance of {@link MetadataType }
     */
    @objid ("a77e4065-5517-4c89-9cca-13cfe3c386b0")
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link Resource }
     */
    @objid ("9bddf1dd-6ba8-40cf-b970-039479d76ac6")
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link PreservedLangStringType }
     */
    @objid ("52d3627a-50ab-423c-ae19-a7d8b7940799")
    public PreservedLangStringType createPreservedLangStringType() {
        return new PreservedLangStringType();
    }

    /**
     * Create an instance of {@link Representation }
     */
    @objid ("9829473c-1bda-4c26-880b-ff4fcb340634")
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link DataObject }
     */
    @objid ("db6527ce-de8e-4137-b795-7a79715f4ab5")
    public DataObject createDataObject() {
        return new DataObject();
    }

    /**
     * Create an instance of {@link Realization }
     */
    @objid ("7e20530f-dfc7-4044-a2d8-c43be531eaf2")
    public Realization createRealization() {
        return new Realization();
    }

    /**
     * Create an instance of {@link Gap }
     */
    @objid ("68de8c09-87fb-40f9-9af9-03e2f886b4c8")
    public Gap createGap() {
        return new Gap();
    }

    /**
     * Create an instance of {@link Value }
     */
    @objid ("2f401fb0-f0b0-43dc-8f20-3387c910dca3")
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link BusinessInterface }
     */
    @objid ("ee265fb2-d78a-427c-b1be-e1cebade8f1b")
    public BusinessInterface createBusinessInterface() {
        return new BusinessInterface();
    }

    /**
     * Create an instance of {@link ApplicationProcess }
     */
    @objid ("103bb192-738b-4f2e-a08c-531f45252b98")
    public ApplicationProcess createApplicationProcess() {
        return new ApplicationProcess();
    }

    /**
     * Create an instance of {@link TechnologyService }
     */
    @objid ("654bb979-cc42-4f03-82b7-fff03b1dfed1")
    public TechnologyService createTechnologyService() {
        return new TechnologyService();
    }

    /**
     * Create an instance of {@link BusinessRole }
     */
    @objid ("771e6462-a21f-4b79-96c7-efb9f39f11e8")
    public BusinessRole createBusinessRole() {
        return new BusinessRole();
    }

    /**
     * Create an instance of {@link Assessment }
     */
    @objid ("edfa22b8-29cf-431d-a3fc-44b05da754df")
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link Element }
     */
    @objid ("e52450bc-a207-4ef1-88c0-de6c648275f3")
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link SystemSoftware }
     */
    @objid ("395cd35f-d9d1-4ca2-a9f1-7489f41209b1")
    public SystemSoftware createSystemSoftware() {
        return new SystemSoftware();
    }

    /**
     * Create an instance of {@link Driver }
     */
    @objid ("8533a165-48af-495b-bcc9-e789e6dd5636")
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link PropertyDefinitionsType }
     */
    @objid ("c6a3a769-d708-4a24-93a1-b2064f4fa305")
    public PropertyDefinitionsType createPropertyDefinitionsType() {
        return new PropertyDefinitionsType();
    }

    /**
     * Create an instance of {@link NestingRelationship }
     */
    @objid ("9f963fb0-15db-440f-a76d-b0fffb4851dd")
    public NestingRelationship createNestingRelationship() {
        return new NestingRelationship();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     */
    @objid ("505ec23a-2de2-4f3b-a6cc-66246e7bcb99")
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link ApplicationInterface }
     */
    @objid ("89ab075a-7b8e-4a38-9a7d-662eb8dba0e2")
    public ApplicationInterface createApplicationInterface() {
        return new ApplicationInterface();
    }

    /**
     * Create an instance of {@link RGBColorType }
     */
    @objid ("c8d351c6-8111-4479-8f0a-6297c92dd9a9")
    public RGBColorType createRGBColorType() {
        return new RGBColorType();
    }

    /**
     * Create an instance of {@link AllowedElementTypeType }
     */
    @objid ("85794681-686d-4ca8-ae38-0f49e3e84dd6")
    public AllowedElementTypeType createAllowedElementTypeType() {
        return new AllowedElementTypeType();
    }

    /**
     * Create an instance of {@link TechnologyEvent }
     */
    @objid ("c20b86e4-d7f0-416b-a394-7d3e23053db8")
    public TechnologyEvent createTechnologyEvent() {
        return new TechnologyEvent();
    }

    /**
     * Create an instance of {@link Composition }
     */
    @objid ("34852350-a9fe-40ac-ba6b-d9b65c0e85fa")
    public Composition createComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link ModelingNoteType }
     */
    @objid ("9ec1ea87-9649-4e53-be6f-e8ed6f940c57")
    public ModelingNoteType createModelingNoteType() {
        return new ModelingNoteType();
    }

    /**
     * Create an instance of {@link CourseOfAction }
     */
    @objid ("0473fd71-8ace-4863-861a-dc8a4f918cb1")
    public CourseOfAction createCourseOfAction() {
        return new CourseOfAction();
    }

    /**
     * Create an instance of {@link Material }
     */
    @objid ("c89d556f-4537-4e24-9a49-f10bec384d83")
    public Material createMaterial() {
        return new Material();
    }

    /**
     * Create an instance of {@link OrganizationType }
     */
    @objid ("d4a2aeb8-8836-445b-92e2-0670e0757f7a")
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link FontType }
     */
    @objid ("f17ae40b-6831-4a99-bc67-761f867e7abd")
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link BusinessService }
     */
    @objid ("f556287b-47e1-431f-9f7b-d415e652119d")
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link Equipment }
     */
    @objid ("842972f0-5be6-4373-8e8d-b61cd02c33eb")
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link ApplicationInteraction }
     */
    @objid ("6b06716c-07ff-4d6d-8946-64523bb9b525")
    public ApplicationInteraction createApplicationInteraction() {
        return new ApplicationInteraction();
    }

    /**
     * Create an instance of {@link LocationType }
     */
    @objid ("c6975ebd-41e8-4176-bc73-cf9c25e56665")
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link Meaning }
     */
    @objid ("7f3955d3-3baa-4f6a-a2c0-3f5a83b5ef1a")
    public Meaning createMeaning() {
        return new Meaning();
    }

    /**
     * Create an instance of {@link BusinessProcess }
     */
    @objid ("7cc0a235-bb1b-4efa-8e2d-1edd91cdbab6")
    public BusinessProcess createBusinessProcess() {
        return new BusinessProcess();
    }

    /**
     * Create an instance of {@link Location }
     */
    @objid ("ee3c8821-64ce-41f6-bb0d-90e6341bd9d0")
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link OriginalViewsType }
     */
    @objid ("4187072b-affe-49d0-9a7d-640ac486df3c")
    public OriginalViewsType createOriginalViewsType() {
        return new OriginalViewsType();
    }

    /**
     * Create an instance of {@link OriginalModelType }
     */
    @objid ("a247a5e7-e706-4487-99a8-df8e4ea60c4a")
    public OriginalModelType createOriginalModelType() {
        return new OriginalModelType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}}
     */
    @objid ("be34841b-bf4e-47a6-9682-b1c8f93b435a")
    @XmlElementDecl(namespace = "http://www.opengroup.org/xsd/archimate/3.0/", name = "model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

}
