/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * This is a container for all of the Views in the model.
 *
 *
 * <p>Java class for ViewsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ViewsType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="viewpoints" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointsType" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("8c1cd59f-4cc4-499d-bfd0-dca4fd401865")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "viewpoints"
})
@XmlSeeAlso({
    ViewsType.class
})
public class OriginalViewsType {
    @objid ("eff1cf7a-113f-4f45-8290-c3312f4d0367")
    protected ViewpointsType viewpoints;

    /**
     * Gets the value of the viewpoints property.
     *
     * @return possible object is
     * {@link ViewpointsType }
     */
    @objid ("b11fb078-c0a3-4086-8784-6793640a0534")
    public ViewpointsType getViewpoints() {
        return viewpoints;
    }

    /**
     * Sets the value of the viewpoints property.
     *
     * @param value allowed object is
     * {@link ViewpointsType }
     */
    @objid ("7f27c20a-5b22-4865-aafa-fe7b7b69175c")
    public void setViewpoints(ViewpointsType value) {
        this.viewpoints = value;
    }

}
