/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * This is the root model type.
 * It is a container for the elements, relationships, diagrams and organizations of the model.
 *
 *
 * <p>Java class for ModelType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ModelType">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}NamedReferenceableType">
 * &lt;sequence>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate/3.0/}PropertiesGroup"/>
 * &lt;element name="metadata" type="{http://www.opengroup.org/xsd/archimate/3.0/}MetadataType" minOccurs="0"/>
 * &lt;element name="elements" type="{http://www.opengroup.org/xsd/archimate/3.0/}ElementsType" minOccurs="0"/>
 * &lt;element name="relationships" type="{http://www.opengroup.org/xsd/archimate/3.0/}RelationshipsType" minOccurs="0"/>
 * &lt;element name="organizations" type="{http://www.opengroup.org/xsd/archimate/3.0/}OrganizationsType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="propertyDefinitions" type="{http://www.opengroup.org/xsd/archimate/3.0/}PropertyDefinitionsType" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("d7c5f2c5-2e2c-4a9d-a40a-f6edfbf83a42")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties",
    "metadata",
    "elements",
    "relationships",
    "organizations",
    "propertyDefinitions"
})
@XmlSeeAlso({
    ModelType.class
})
public class OriginalModelType extends NamedReferenceableType {
    @objid ("6309beac-3d52-45af-9c09-721480d951c1")
    @XmlAttribute(name = "version")
    protected String version;

    @objid ("64af0648-d137-41c4-bbb7-ac3d22d0077e")
    protected PropertiesType properties;

    @objid ("c71867b4-395a-4b87-91a3-6ee5a43fc526")
    protected MetadataType metadata;

    @objid ("00611181-cee1-4f46-971b-bcec3fa3edee")
    protected ElementsType elements;

    @objid ("b1a434a8-6c47-41be-b14b-fce1717b1a8b")
    protected RelationshipsType relationships;

    @objid ("17877780-1871-47b6-ad39-ef68d5754547")
    protected List<OrganizationsType> organizations;

    @objid ("e29633af-34cf-43e1-962b-92ed2d159c98")
    protected PropertyDefinitionsType propertyDefinitions;

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("3ff5be99-3ce9-417b-8509-99e5c596e830")
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("ee8f7842-5152-455e-8aed-edf38f1a32d2")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the metadata property.
     *
     * @return possible object is
     * {@link MetadataType }
     */
    @objid ("20cea7e3-9648-48e0-b477-a67030daadc7")
    public MetadataType getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     *
     * @param value allowed object is
     * {@link MetadataType }
     */
    @objid ("bbebce11-a67a-403b-9cce-c549a53ee126")
    public void setMetadata(MetadataType value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the elements property.
     *
     * @return possible object is
     * {@link ElementsType }
     */
    @objid ("73904782-c5b0-436b-82ca-7ff18fae9e2f")
    public ElementsType getElements() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     *
     * @param value allowed object is
     * {@link ElementsType }
     */
    @objid ("00d08eed-cd7c-47e2-84fe-029e7aad9a3b")
    public void setElements(ElementsType value) {
        this.elements = value;
    }

    /**
     * Gets the value of the relationships property.
     *
     * @return possible object is
     * {@link RelationshipsType }
     */
    @objid ("0659d8ee-656d-4367-ab2b-dcf36f72fe33")
    public RelationshipsType getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     *
     * @param value allowed object is
     * {@link RelationshipsType }
     */
    @objid ("156f0e00-8b03-4cbb-8062-a3f2432a0b23")
    public void setRelationships(RelationshipsType value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the organizations property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizations property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganizations().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationsType }
     */
    @objid ("f830d473-f298-4610-8df3-d1d6fc835130")
    public List<OrganizationsType> getOrganizations() {
        if (organizations == null) {
            organizations = new ArrayList<OrganizationsType>();
        }
        return this.organizations;
    }

    /**
     * Gets the value of the propertyDefinitions property.
     *
     * @return possible object is
     * {@link PropertyDefinitionsType }
     */
    @objid ("336debe4-cdc0-4a3a-9a7c-7f50c4f19c15")
    public PropertyDefinitionsType getPropertyDefinitions() {
        return propertyDefinitions;
    }

    /**
     * Sets the value of the propertyDefinitions property.
     *
     * @param value allowed object is
     * {@link PropertyDefinitionsType }
     */
    @objid ("20510e87-f624-41bc-88c9-17eb98cdbbce")
    public void setPropertyDefinitions(PropertyDefinitionsType value) {
        this.propertyDefinitions = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("4e7a4279-013d-4b0f-b25e-5c79dbb24dcb")
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("7d4a8fe8-4134-417b-9a5b-d96ddbed8c7a")
    public void setVersion(String value) {
        this.version = value;
    }

}
