/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for RelationshipTypeEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelationshipTypeEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Composition"/>
 * &lt;enumeration value="Aggregation"/>
 * &lt;enumeration value="Assignment"/>
 * &lt;enumeration value="Realization"/>
 * &lt;enumeration value="Serving"/>
 * &lt;enumeration value="Access"/>
 * &lt;enumeration value="Influence"/>
 * &lt;enumeration value="Triggering"/>
 * &lt;enumeration value="Flow"/>
 * &lt;enumeration value="Specialization"/>
 * &lt;enumeration value="Association"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("dbf80a53-f90e-4060-9b78-6add9e89f8bf")
@XmlType(name = "RelationshipTypeEnum")
@XmlEnum
public enum RelationshipTypeEnum {
    @objid ("965ac4c2-e253-43dd-82d8-4bc6c6a3beef")
    @XmlEnumValue("Composition")
    COMPOSITION("Composition"),
    @objid ("308e0e50-d5c5-4a9d-b27f-8ea72d029c0c")
    @XmlEnumValue("Aggregation")
    AGGREGATION("Aggregation"),
    @objid ("90dd137c-17a9-4b74-9d2c-4c3ba9ef1a27")
    @XmlEnumValue("Assignment")
    ASSIGNMENT("Assignment"),
    @objid ("8566fbf3-0fc9-43ae-978f-d55928c482c2")
    @XmlEnumValue("Realization")
    REALIZATION("Realization"),
    @objid ("f2a7f01e-566b-4bf0-a822-ad6a0eba5ff8")
    @XmlEnumValue("Serving")
    SERVING("Serving"),
    @objid ("ef5bce4a-e4e3-449b-a3ce-d08de913d0af")
    @XmlEnumValue("Access")
    ACCESS("Access"),
    @objid ("14a9450f-f1f5-4456-acd7-1e712dae9ea5")
    @XmlEnumValue("Influence")
    INFLUENCE("Influence"),
    @objid ("4dfad49a-a776-4b36-91e7-c653794e9eab")
    @XmlEnumValue("Triggering")
    TRIGGERING("Triggering"),
    @objid ("4a5ab4d9-d01f-42a7-a6bb-215376a2bb5f")
    @XmlEnumValue("Flow")
    FLOW("Flow"),
    @objid ("4c0d9a17-48c7-445a-a4fa-87f4dfc920f3")
    @XmlEnumValue("Specialization")
    SPECIALIZATION("Specialization"),
    @objid ("15094a9f-df16-44dd-95b8-f5441aa1f392")
    @XmlEnumValue("Association")
    ASSOCIATION("Association");

    @objid ("cfb54876-5adc-4e89-a2a1-bc064e3ecc46")
    private final String value;

    @objid ("44778e11-9f11-4932-9e67-75610d645545")
    RelationshipTypeEnum(String v) {
        value = v;
    }

    @objid ("a2c00b48-6fc7-4f1f-935b-a3a42bd0bc39")
    public String value() {
        return value;
    }

    @objid ("a11ce342-bb88-497d-a068-655b4d850902")
    public static RelationshipTypeEnum fromValue(String v) {
        for (RelationshipTypeEnum c: RelationshipTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
