/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Connector for a Relationship.
 *
 *
 * <p>Java class for Relationship complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Relationship">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}SourcedConnectionType">
 * &lt;attribute name="relationshipRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("4270642d-4c00-4856-ab6d-3330341d58bc")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Relationship")
@XmlSeeAlso({
    NestingRelationship.class
})
public class Relationship extends SourcedConnectionType {
    @objid ("eb607f40-9b0d-4d9d-9876-667cd5c55558")
    @XmlAttribute(name = "relationshipRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relationshipRef;

    /**
     * Gets the value of the relationshipRef property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("5c1148e8-1144-4807-9303-b7350d2d0b41")
    public Object getRelationshipRef() {
        return relationshipRef;
    }

    /**
     * Sets the value of the relationshipRef property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("fdf8a2cd-a27b-4057-a72e-de8330930be2")
    public void setRelationshipRef(Object value) {
        this.relationshipRef = value;
    }

}
