/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for RelationshipConnectorEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelationshipConnectorEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="AndJunction"/>
 * &lt;enumeration value="OrJunction"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("38943489-3bb5-4fb3-a9bf-bf4d42c03da6")
@XmlType(name = "RelationshipConnectorEnum")
@XmlEnum
public enum RelationshipConnectorEnum {
    @objid ("bc66a73a-eee5-44e9-89ea-b514cbb932e4")
    @XmlEnumValue("AndJunction")
    AND_JUNCTION("AndJunction"),
    @objid ("f8a33fde-440c-4b79-9c61-f14cfad01577")
    @XmlEnumValue("OrJunction")
    OR_JUNCTION("OrJunction");

    @objid ("3449dae3-0fcd-4c81-a717-9589255ea032")
    private final String value;

    @objid ("08124a8f-c7c7-4380-ba61-6144e1152cd6")
    RelationshipConnectorEnum(String v) {
        value = v;
    }

    @objid ("ac111ec8-3b66-4020-a3c4-4ab41f5c6508")
    public String value() {
        return value;
    }

    @objid ("12fca991-50f0-48d0-9a9c-03dcce47bb78")
    public static RelationshipConnectorEnum fromValue(String v) {
        for (RelationshipConnectorEnum c: RelationshipConnectorEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
