/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * RGB Color type.
 * The r, g, b attributes range from 0 - 255.
 * The a (alpha) transparency attribute is optional. 0 = full transparency, 100 = opaque.
 *
 *
 * <p>Java class for RGBColorType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RGBColorType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="r" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" />
 * &lt;attribute name="g" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" />
 * &lt;attribute name="b" use="required" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBValueType" />
 * &lt;attribute name="a">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("d47a4a4b-465b-402b-9bae-8552aee133fb")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RGBColorType")
public class RGBColorType {
    @objid ("0ca30fa4-6be3-471d-ab8a-bc2736690c92")
    @XmlAttribute(name = "r", required = true)
    protected short r;

    @objid ("f9fbdb27-f20a-4e32-985c-07700571103f")
    @XmlAttribute(name = "g", required = true)
    protected short g;

    @objid ("c071b78f-8c3e-4ef4-bf80-e2792a7f9206")
    @XmlAttribute(name = "b", required = true)
    protected short b;

    @objid ("750f396e-ef2f-413f-983a-4d84814f26ea")
    @XmlAttribute(name = "a")
    protected Short a;

    /**
     * Gets the value of the r property.
     */
    @objid ("81afea60-9e59-402a-9004-e3401ea488bf")
    public short getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     */
    @objid ("20c9c40d-2a30-4f9b-9077-4f9de7d7eb70")
    public void setR(short value) {
        this.r = value;
    }

    /**
     * Gets the value of the g property.
     */
    @objid ("e3641f89-b821-4fa2-b39f-a810cb6bfaef")
    public short getG() {
        return g;
    }

    /**
     * Sets the value of the g property.
     */
    @objid ("00b3bc29-540e-4c9b-bf53-3357fa96a2b6")
    public void setG(short value) {
        this.g = value;
    }

    /**
     * Gets the value of the b property.
     */
    @objid ("d7986132-44a2-4670-bd56-844929ab660b")
    public short getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     */
    @objid ("44a20fe7-6570-4ca1-bb54-efe95c346eac")
    public void setB(short value) {
        this.b = value;
    }

    /**
     * Gets the value of the a property.
     *
     * @return possible object is
     * {@link Short }
     */
    @objid ("7c70d7be-4ac7-4f0b-ac76-694363647cc9")
    public Short getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     *
     * @param value allowed object is
     * {@link Short }
     */
    @objid ("1dc6a7ba-340c-47e7-846b-3d46af96d1ba")
    public void setA(Short value) {
        this.a = value;
    }

}
