/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * This is a container for all of the Stakeholders in the Concern.
 *
 *
 * <p>Java class for StakeholdersType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StakeholdersType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="stakeholder" type="{http://www.opengroup.org/xsd/archimate/3.0/}StakeholderType" maxOccurs="unbounded"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("ae5a4c3f-d06c-4df7-815e-fb298d687d35")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StakeholdersType", propOrder = {
    "stakeholder"
})
public class StakeholdersType {
    @objid ("33e84afd-d8c2-4206-afa5-f578fd21b5da")
    @XmlElement(required = true)
    protected List<StakeholderType> stakeholder;

    /**
     * Gets the value of the stakeholder property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stakeholder property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getStakeholder().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StakeholderType }
     */
    @objid ("e15b7fb4-da32-43d6-a084-04ba120e5874")
    public List<StakeholderType> getStakeholder() {
        if (stakeholder == null) {
            stakeholder = new ArrayList<StakeholderType>();
        }
        return this.stakeholder;
    }

}
