/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.math.BigInteger;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * A Style type for a node and a connection.
 * It is a container for style properties such as color, font.
 *
 *
 * <p>Java class for StyleType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StyleType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;all>
 * &lt;element name="lineColor" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBColorType" minOccurs="0"/>
 * &lt;element name="fillColor" type="{http://www.opengroup.org/xsd/archimate/3.0/}RGBColorType" minOccurs="0"/>
 * &lt;element name="font" type="{http://www.opengroup.org/xsd/archimate/3.0/}FontType" minOccurs="0"/>
 * &lt;/all>
 * &lt;attribute name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("4ba09589-9b5b-4aa3-9554-7607be271970")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StyleType", propOrder = {

})
public class StyleType {
    @objid ("b0b8de46-1218-40c1-89dd-2fee9d0cfed1")
    protected RGBColorType lineColor;

    @objid ("5c7b4875-b69c-4b77-834e-d53c74de7dd8")
    protected RGBColorType fillColor;

    @objid ("32c49891-3541-4cbe-b6d4-ea5e9fe2c5eb")
    protected FontType font;

    @objid ("022d0b3a-dac7-46cb-9510-9e8ebf6229d7")
    @XmlAttribute(name = "lineWidth")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lineWidth;

    /**
     * Gets the value of the lineColor property.
     *
     * @return possible object is
     * {@link RGBColorType }
     */
    @objid ("d584a48e-709e-4f84-9de4-5837f355dec7")
    public RGBColorType getLineColor() {
        return lineColor;
    }

    /**
     * Sets the value of the lineColor property.
     *
     * @param value allowed object is
     * {@link RGBColorType }
     */
    @objid ("2c3a9915-d473-4a19-add3-f3126d95ced9")
    public void setLineColor(RGBColorType value) {
        this.lineColor = value;
    }

    /**
     * Gets the value of the fillColor property.
     *
     * @return possible object is
     * {@link RGBColorType }
     */
    @objid ("c801fe28-4275-4b8b-a88d-efdc857b6616")
    public RGBColorType getFillColor() {
        return fillColor;
    }

    /**
     * Sets the value of the fillColor property.
     *
     * @param value allowed object is
     * {@link RGBColorType }
     */
    @objid ("cb7f88c9-98c5-4d7d-aca3-f62149a61dac")
    public void setFillColor(RGBColorType value) {
        this.fillColor = value;
    }

    /**
     * Gets the value of the font property.
     *
     * @return possible object is
     * {@link FontType }
     */
    @objid ("6a9e1299-43ba-4b3e-976c-6d87a6568d59")
    public FontType getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     *
     * @param value allowed object is
     * {@link FontType }
     */
    @objid ("7c1df94b-f18c-4d77-b487-2fcc11dbfc54")
    public void setFont(FontType value) {
        this.font = value;
    }

    /**
     * Gets the value of the lineWidth property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("2cbcf165-3151-4724-ae14-937d8e79f457")
    public BigInteger getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("b250abc4-b396-469a-9703-6ed054a6cb0f")
    public void setLineWidth(BigInteger value) {
        this.lineWidth = value;
    }

}
