/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ViewpointContentEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ViewpointContentEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Details"/>
 * &lt;enumeration value="Coherence"/>
 * &lt;enumeration value="Overview"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("acc16751-31a2-49f5-aca6-854a0ed8c967")
@XmlType(name = "ViewpointContentEnum")
@XmlEnum
public enum ViewpointContentEnum {
    @objid ("543242a3-005f-4f4c-87bc-55e76698e8ed")
    @XmlEnumValue("Details")
    DETAILS("Details"),
    @objid ("a028d721-28f0-4151-9966-0bdee8dfb770")
    @XmlEnumValue("Coherence")
    COHERENCE("Coherence"),
    @objid ("27da9115-13db-4f5d-a13d-29584aff7a82")
    @XmlEnumValue("Overview")
    OVERVIEW("Overview");

    @objid ("bd819b77-354a-4f83-b555-43dc88ddd258")
    private final String value;

    @objid ("628d9cde-27a3-4773-ac0e-ad0525362c87")
    ViewpointContentEnum(String v) {
        value = v;
    }

    @objid ("538ef90a-45b6-486a-9ebe-df2c63b81169")
    public String value() {
        return value;
    }

    @objid ("24add4cf-68e7-4192-9f39-ea3e6305d816")
    public static ViewpointContentEnum fromValue(String v) {
        for (ViewpointContentEnum c: ViewpointContentEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
