/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ViewpointPurposeEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ViewpointPurposeEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 * &lt;enumeration value="Designing"/>
 * &lt;enumeration value="Deciding"/>
 * &lt;enumeration value="Informing"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("338e7e04-82e5-4227-a95a-3334f6032964")
@XmlType(name = "ViewpointPurposeEnum")
@XmlEnum
public enum ViewpointPurposeEnum {
    @objid ("a2f99b9a-e8a1-4caf-a082-8a679896529c")
    @XmlEnumValue("Designing")
    DESIGNING("Designing"),
    @objid ("7fa2c0bb-60ed-4cb7-940f-278bdede59b1")
    @XmlEnumValue("Deciding")
    DECIDING("Deciding"),
    @objid ("5ea83b82-df41-4d85-9256-78d220a28f50")
    @XmlEnumValue("Informing")
    INFORMING("Informing");

    @objid ("be5f14e0-ae32-4110-939c-0245a9465db3")
    private final String value;

    @objid ("6eb28de5-b8a3-4cb3-bf43-634e723fc498")
    ViewpointPurposeEnum(String v) {
        value = v;
    }

    @objid ("15dc3e2f-3db2-4219-9488-36eb6f77b008")
    public String value() {
        return value;
    }

    @objid ("b52655f1-ddb9-4d0d-b0f9-6a780701c79a")
    public static ViewpointPurposeEnum fromValue(String v) {
        for (ViewpointPurposeEnum c: ViewpointPurposeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
