/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.math.BigInteger;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Graphical node type. It can contain child node types.
 *
 *
 * <p>Java class for ViewNodeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ViewNodeType">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}ViewConceptType">
 * &lt;attGroup ref="{http://www.opengroup.org/xsd/archimate/3.0/}SizeGroup"/>
 * &lt;attGroup ref="{http://www.opengroup.org/xsd/archimate/3.0/}LocationGroup"/>
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("a3d796f2-78d8-4f5e-994b-a079564dca1d")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewNodeType")
@XmlSeeAlso({
    Label.class,
    Container.class
})
public abstract class ViewNodeType extends ViewConceptType {
    @objid ("ac0febc5-c96f-4ea7-ad55-9182e43975dd")
    @XmlAttribute(name = "x", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger x;

    @objid ("f472c2bf-ddcd-46c1-b7e7-546bf338b5ae")
    @XmlAttribute(name = "y", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger y;

    @objid ("dd3b8d8b-1d03-4f43-a59c-7cf4a3c9b1e2")
    @XmlAttribute(name = "w", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger w;

    @objid ("be7f7235-f2dc-4438-86e0-f28f8560e7db")
    @XmlAttribute(name = "h", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger h;

    /**
     * Gets the value of the x property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("d8dc96c8-0ef5-45c9-9554-080b4912da4e")
    public BigInteger getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("dbe4b5ad-ca13-4f79-8232-d809edd8a094")
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("fd64365b-5745-4973-a600-132bd0b37c04")
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("20cb7c33-2f6e-4871-8b18-74f7b05f6fe8")
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the w property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("6c51fe18-0183-476d-b29d-3fd132f117f2")
    public BigInteger getW() {
        return w;
    }

    /**
     * Sets the value of the w property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("e1762f2e-496b-4535-82de-666573d29eda")
    public void setW(BigInteger value) {
        this.w = value;
    }

    /**
     * Gets the value of the h property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("b0ef4d64-a0d0-4c33-a807-fab87e79613d")
    public BigInteger getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("de4fd6e9-1f1f-4ead-b8d1-97388dc6ae80")
    public void setH(BigInteger value) {
        this.h = value;
    }

}
