/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Container for View type.
 *
 * Note that View itself is abstract so one must have a derived type. the xml example must look like
 * a tag name "view" with an attribute of xsi:type="Diagram", if Diagram is a derived type from ViewType.
 *
 *
 * <p>Java class for ViewType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ViewType">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}NamedReferenceableType">
 * &lt;sequence>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate/3.0/}PropertiesGroup"/>
 * &lt;/sequence>
 * &lt;attribute name="viewpoint" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointTypeType" />
 * &lt;attribute name="viewpointRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("48dbb465-14dc-445e-aa82-8a5411f1d342")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewType", propOrder = {
    "properties"
})
@XmlSeeAlso({
    Diagram.class
})
public abstract class ViewType extends NamedReferenceableType {
    @objid ("a5ff93c5-1c40-4b1a-9b9d-dbfae129461f")
    @XmlAttribute(name = "viewpoint")
    protected String viewpoint;

    @objid ("d7a7a8c6-2161-4baa-a2c5-3d567421de92")
    protected PropertiesType properties;

    @objid ("190f4d87-c568-49a2-b597-bbe6da18b51e")
    @XmlAttribute(name = "viewpointRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object viewpointRef;

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("de47d448-c618-481e-82ba-29c99556a762")
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("a48399d8-c38f-4328-99b9-882e8ffefd0a")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the viewpoint property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("285cae66-eb48-49aa-b56e-aa3d90f52fb4")
    public String getViewpoint() {
        return viewpoint;
    }

    /**
     * Sets the value of the viewpoint property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("3c9518b9-c79f-4eff-a8d6-332a6e2435bf")
    public void setViewpoint(String value) {
        this.viewpoint = value;
    }

    /**
     * Gets the value of the viewpointRef property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("a86b09cd-7480-447f-bb21-bcb3f2e8e122")
    public Object getViewpointRef() {
        return viewpointRef;
    }

    /**
     * Sets the value of the viewpointRef property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("dcb95901-b5d6-41e9-98a2-3fff442c1169")
    public void setViewpointRef(Object value) {
        this.viewpointRef = value;
    }

}
