/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlList;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ViewpointType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ViewpointType">
 * &lt;complexContent>
 * &lt;extension base="{http://www.opengroup.org/xsd/archimate/3.0/}NamedReferenceableType">
 * &lt;sequence>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate/3.0/}PropertiesGroup"/>
 * &lt;element name="concern" type="{http://www.opengroup.org/xsd/archimate/3.0/}ConcernType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="viewpointPurpose" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointPurposeType" minOccurs="0"/>
 * &lt;element name="viewpointContent" type="{http://www.opengroup.org/xsd/archimate/3.0/}ViewpointContentType" minOccurs="0"/>
 * &lt;element name="allowedElementType" type="{http://www.opengroup.org/xsd/archimate/3.0/}AllowedElementTypeType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="allowedRelationshipType" type="{http://www.opengroup.org/xsd/archimate/3.0/}AllowedRelationshipTypeType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="modelingNote" type="{http://www.opengroup.org/xsd/archimate/3.0/}ModelingNoteType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/extension>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("8e621411-2b54-4ff5-80e5-748aa8391d3a")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewpointType", propOrder = {
    "properties",
    "concern",
    "viewpointPurpose",
    "viewpointContent",
    "allowedElementType",
    "allowedRelationshipType",
    "modelingNote"
})
public class ViewpointType extends NamedReferenceableType {
    @objid ("56f50c81-7de6-48f3-9aab-b89360845acf")
    @XmlList
    protected List<ViewpointPurposeEnum> viewpointPurpose;

    @objid ("edc0256d-7d6e-4af4-a656-aa99072fbb72")
    @XmlList
    protected List<ViewpointContentEnum> viewpointContent;

    @objid ("387e31d3-1ca9-44ba-a94a-a688281710fd")
    protected PropertiesType properties;

    @objid ("e5ebd1b6-95ff-4714-81da-ac97a89ed47b")
    protected List<ConcernType> concern;

    @objid ("cc3964e4-4a9e-477e-9e4d-f6e1da025d73")
    protected List<AllowedElementTypeType> allowedElementType;

    @objid ("a3648ed5-6b6d-4a02-9728-ea759b7362f9")
    protected List<AllowedRelationshipTypeType> allowedRelationshipType;

    @objid ("7596bb02-ecde-41c3-b42e-4638997be1a0")
    protected List<ModelingNoteType> modelingNote;

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("88bef9d0-97f0-4def-b3b4-865f0d00b0d6")
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("3483c091-c4b2-4f39-b3fb-5338eb998261")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the concern property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the concern property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getConcern().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConcernType }
     */
    @objid ("9b86efe6-8873-4260-8ac1-885cda6b16c0")
    public List<ConcernType> getConcern() {
        if (concern == null) {
            concern = new ArrayList<ConcernType>();
        }
        return this.concern;
    }

    /**
     * Gets the value of the viewpointPurpose property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewpointPurpose property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getViewpointPurpose().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewpointPurposeEnum }
     */
    @objid ("225d2c91-84b9-4ae3-a084-2c67603779bf")
    public List<ViewpointPurposeEnum> getViewpointPurpose() {
        if (viewpointPurpose == null) {
            viewpointPurpose = new ArrayList<ViewpointPurposeEnum>();
        }
        return this.viewpointPurpose;
    }

    /**
     * Gets the value of the viewpointContent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewpointContent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getViewpointContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewpointContentEnum }
     */
    @objid ("ed8fa6fb-d567-43f4-a777-2f3164620ea3")
    public List<ViewpointContentEnum> getViewpointContent() {
        if (viewpointContent == null) {
            viewpointContent = new ArrayList<ViewpointContentEnum>();
        }
        return this.viewpointContent;
    }

    /**
     * Gets the value of the allowedElementType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedElementType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAllowedElementType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedElementTypeType }
     */
    @objid ("e8389d28-dc48-4a21-988a-778be2f93d6f")
    public List<AllowedElementTypeType> getAllowedElementType() {
        if (allowedElementType == null) {
            allowedElementType = new ArrayList<AllowedElementTypeType>();
        }
        return this.allowedElementType;
    }

    /**
     * Gets the value of the allowedRelationshipType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedRelationshipType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAllowedRelationshipType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedRelationshipTypeType }
     */
    @objid ("0285df67-4217-463c-a728-227e5f1be9c6")
    public List<AllowedRelationshipTypeType> getAllowedRelationshipType() {
        if (allowedRelationshipType == null) {
            allowedRelationshipType = new ArrayList<AllowedRelationshipTypeType>();
        }
        return this.allowedRelationshipType;
    }

    /**
     * Gets the value of the modelingNote property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelingNote property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getModelingNote().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelingNoteType }
     */
    @objid ("84e53625-27ef-47c0-9532-ede0eae9a5ec")
    public List<ModelingNoteType> getModelingNote() {
        if (modelingNote == null) {
            modelingNote = new ArrayList<ModelingNoteType>();
        }
        return this.modelingNote;
    }

}
