/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.15 at 11:24:57 AM CEST
//
package org.modelio.archimate.exchange.v30.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ViewpointsEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ViewpointsEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 * &lt;enumeration value="Organization"/>
 * &lt;enumeration value="Application Platform"/>
 * &lt;enumeration value="Information Structure"/>
 * &lt;enumeration value="Technology"/>
 * &lt;enumeration value="Layered"/>
 * &lt;enumeration value="Physical"/>
 * &lt;enumeration value="Product"/>
 * &lt;enumeration value="Application Usage"/>
 * &lt;enumeration value="Technology Usage"/>
 * &lt;enumeration value="Business Process Cooperation"/>
 * &lt;enumeration value="Application Cooperation"/>
 * &lt;enumeration value="Service Realization"/>
 * &lt;enumeration value="Implementation and Deployment"/>
 * &lt;enumeration value="Goal Realization"/>
 * &lt;enumeration value="Goal Contribution"/>
 * &lt;enumeration value="Principles"/>
 * &lt;enumeration value="Requirements Realization"/>
 * &lt;enumeration value="Motivation"/>
 * &lt;enumeration value="Strategy"/>
 * &lt;enumeration value="Capability Map"/>
 * &lt;enumeration value="Outcome Realization"/>
 * &lt;enumeration value="Resource Map"/>
 * &lt;enumeration value="Project"/>
 * &lt;enumeration value="Migration"/>
 * &lt;enumeration value="Implementation and Migration"/>
 * &lt;enumeration value="Stakeholder"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("ac19f642-6723-4659-b961-0ffa2c884d79")
@XmlType(name = "ViewpointsEnum")
@XmlEnum
public enum ViewpointsEnum {
    @objid ("c460dff0-8027-4cc5-8654-fa5339b70004")
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),
    @objid ("4f832b0c-457f-410e-ae70-750f916d2e13")
    @XmlEnumValue("Application Platform")
    APPLICATION_PLATFORM("Application Platform"),
    @objid ("df5ee5f2-1f6d-4f24-8069-97ec3a19b41a")
    @XmlEnumValue("Information Structure")
    INFORMATION_STRUCTURE("Information Structure"),
    @objid ("bc996f45-cb92-47d8-a456-322d660e8881")
    @XmlEnumValue("Technology")
    TECHNOLOGY("Technology"),
    @objid ("dcf91bd4-b738-46b5-990c-0fd06b2775e7")
    @XmlEnumValue("Layered")
    LAYERED("Layered"),
    @objid ("4a8c8d3d-3787-4673-8e89-f4fe00df693e")
    @XmlEnumValue("Physical")
    PHYSICAL("Physical"),
    @objid ("bfa1a2a3-fdf0-48fa-b298-7a6777134ad9")
    @XmlEnumValue("Product")
    PRODUCT("Product"),
    @objid ("73b7c842-0681-4a72-a2c7-85fc76d09174")
    @XmlEnumValue("Application Usage")
    APPLICATION_USAGE("Application Usage"),
    @objid ("b245e938-682b-49cb-8147-1fe999ae2273")
    @XmlEnumValue("Technology Usage")
    TECHNOLOGY_USAGE("Technology Usage"),
    @objid ("405813db-e841-4263-9de1-84dd5185c576")
    @XmlEnumValue("Business Process Cooperation")
    BUSINESS_PROCESS_COOPERATION("Business Process Cooperation"),
    @objid ("7097714b-e867-4bb0-bcdd-77be9cca2965")
    @XmlEnumValue("Application Cooperation")
    APPLICATION_COOPERATION("Application Cooperation"),
    @objid ("9b67fb61-b2e5-41be-9a5c-1f93a85203b7")
    @XmlEnumValue("Service Realization")
    SERVICE_REALIZATION("Service Realization"),
    @objid ("c1f95873-4711-44e8-84eb-46fcd5aaa9d5")
    @XmlEnumValue("Implementation and Deployment")
    IMPLEMENTATION_AND_DEPLOYMENT("Implementation and Deployment"),
    @objid ("17ca80ca-56fe-4da3-8049-89f5d81fd59d")
    @XmlEnumValue("Goal Realization")
    GOAL_REALIZATION("Goal Realization"),
    @objid ("d70145a6-874a-4222-957f-66f17997dd6e")
    @XmlEnumValue("Goal Contribution")
    GOAL_CONTRIBUTION("Goal Contribution"),
    @objid ("bae14c78-3831-4462-8b77-830e8586bffb")
    @XmlEnumValue("Principles")
    PRINCIPLES("Principles"),
    @objid ("cdaf6840-2573-4933-ab32-1a8f3aefa624")
    @XmlEnumValue("Requirements Realization")
    REQUIREMENTS_REALIZATION("Requirements Realization"),
    @objid ("66930b6c-aa76-4c1c-be40-4ef0b0f9674c")
    @XmlEnumValue("Motivation")
    MOTIVATION("Motivation"),
    @objid ("81a9dd90-94f1-4698-9970-f545038f6e62")
    @XmlEnumValue("Strategy")
    STRATEGY("Strategy"),
    @objid ("a6c73905-eaf3-4c15-8a40-0902b9b41dee")
    @XmlEnumValue("Capability Map")
    CAPABILITY_MAP("Capability Map"),
    @objid ("e2ecf75a-4cd7-45ac-9afe-5d6b83554bc3")
    @XmlEnumValue("Outcome Realization")
    OUTCOME_REALIZATION("Outcome Realization"),
    @objid ("48113c8b-9a19-42cd-a795-bc184c69bfd4")
    @XmlEnumValue("Resource Map")
    RESOURCE_MAP("Resource Map"),
    @objid ("32f4c457-76c3-4d00-9b1d-1e2618a87293")
    @XmlEnumValue("Project")
    PROJECT("Project"),
    @objid ("b45b6093-182d-41fd-8529-db0436738b15")
    @XmlEnumValue("Migration")
    MIGRATION("Migration"),
    @objid ("e13efe35-7fc3-4b73-8c90-4ca7c33d28e0")
    @XmlEnumValue("Implementation and Migration")
    IMPLEMENTATION_AND_MIGRATION("Implementation and Migration"),
    @objid ("393a0e8d-3ae3-4929-8723-089214f15be3")
    @XmlEnumValue("Stakeholder")
    STAKEHOLDER("Stakeholder");

    @objid ("bd53a493-6d29-4e5e-870f-39c52837f6d7")
    private final String value;

    @objid ("e507a0ca-e491-486a-ac4a-c23390adcf3b")
    ViewpointsEnum(String v) {
        value = v;
    }

    @objid ("1a867263-9e43-4b29-bbee-2060d5e1d4db")
    public String value() {
        return value;
    }

    @objid ("3b91686e-4dc8-4639-9924-fb4975e68bd2")
    public static ViewpointsEnum fromValue(String v) {
        for (ViewpointsEnum c: ViewpointsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
