/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* WARNING: GENERATED FILE -  DO NOT EDIT
     Metamodel: Archimate, version 1.0.4, by Modeliosoft
     Generator version: 3.14.00
     Generated on: Feb 9, 2023
*/
package org.modelio.archimate.metamodel.layers.business.behavior;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import org.modelio.archimate.metamodel.core.generic.Event;

/**
 * BusinessEvent vnull
 *
 *
 * <p>Business processes and other business behavior may be triggered or interrupted by a business&nbsp;event. Also, business processes may raise events that trigger other business processes, functions,&nbsp;or interactions. Unlike business processes, functions, and interactions, a business event is&nbsp;instantaneous: it does not have duration. Events may originate from the environment of the&nbsp;organization (e.g., from a customer), but also internal events may occur generated by, for&nbsp;example, other processes within the organization.</p><p>A business event may have a time attribute that denotes the moment or moments at which the&nbsp;event happens. For example, this can be used to model time schedules; e.g., to model an event&nbsp;that triggers a recurring business process to execute every first Monday of the month.</p><p>A business event may trigger or be triggered (raised) by a business process, business function, or&nbsp;business interaction. A business event may access a business object and may be composed of&nbsp;other business events. The name of a business event should preferably be a verb in the perfect&nbsp;tense; e.g., claim received.</p>
 *
 *
 */
@objid ("5c4e943f-99ea-4cad-bb29-087a98f0bf30")
public interface BusinessEvent extends Event {
    /**
     * The metaclass simple name.
     */
    @objid ("b1664821-f5d5-4458-b454-9bc30c3a28a5")
    public static final String MNAME = "BusinessEvent";

    /**
     * The metaclass qualified name.
     */
    @objid ("6ecd5723-340a-4e8d-81e2-c99397020891")
    public static final String MQNAME = "Archimate.BusinessEvent";

}
