/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* WARNING: GENERATED FILE -  DO NOT EDIT
     Metamodel: Archimate, version 1.0.4, by Modeliosoft
     Generator version: 3.14.00
     Generated on: Feb 9, 2023
*/
package org.modelio.archimate.metamodel.layers.technology.behavior;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import org.modelio.archimate.metamodel.core.generic.Event;

/**
 * TechnologyEvent vnull
 *
 *
 * <p>Technology functions and other technology behavior may be triggered or interrupted by a&nbsp;technology event. Also, technology functions may raise events that trigger other infrastructure&nbsp;behavior. Unlike processes, functions, and interactions, an event is instantaneous: it does not&nbsp;have duration. Events may originate from the environment of the organization, but also internal&nbsp;events may occur generated by, for example, other devices within the organization.</p><p>A technology event may have a time attribute that denotes the moment or moments at which the&nbsp;event happens. For example, this can be used to model time schedules; e.g., to model an event&nbsp;that triggers a recurring infrastructure function such as making a daily backup.</p><p>A technology event may trigger or be triggered (raised) by a technology function, process, or&nbsp;interaction. A technology event may access a data object and may be composed of other&nbsp;technology events. The name of a technology event should preferably be a verb in the perfect&nbsp;tense; e.g., &quot;message received&quot;.</p>
 *
 *
 */
@objid ("a00511de-73a2-438c-8331-c3c0864d539d")
public interface TechnologyEvent extends Event {
    /**
     * The metaclass simple name.
     */
    @objid ("0604058a-d3d5-407f-95bb-8b28fe7ccb7b")
    public static final String MNAME = "TechnologyEvent";

    /**
     * The metaclass qualified name.
     */
    @objid ("72c04279-4756-4fc5-889b-3dfcadf73c39")
    public static final String MQNAME = "Archimate.TechnologyEvent";

}
