source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               e4model/,\
               plugin.xml,\
               res/,\
               plugin.properties,plugin_fr.properties,\
               images/,\
               icons/
