#Product Runtime Configuration File
eclipse.application=org.eclipse.help.base.infocenterApplication
osgi.bundles.defaultStartLevel=4
eclipse.product=org.modelio.infocenter.infocenterModelioHelp
osgi.splashPath=platform:/base/plugins/org.modelio.infocenter
osgi.bundles=  com.ibm.icu@start,\
  com.jcraft.jsch@start,\
  javax.el@start,\
  javax.servlet@start,\
  javax.servlet.jsp@start,\
  org.apache.commons.logging@start,\
  org.apache.felix.gogo.runtime@start,\
  org.apache.felix.gogo.shell@start,\
  org.apache.jasper.glassfish@start,\
  org.apache.lucene.analysis@start,\
  org.apache.lucene.analyzers-common@start,\
  org.apache.lucene.analyzers-smartcn@start,\
  org.apache.lucene.core@start,\
  org.eclipse.core.contenttype@start,\
  org.eclipse.core.expressions@start,\
  org.eclipse.core.jobs@start,\
  org.eclipse.core.net@start,\
  org.eclipse.core.runtime@start,\
  org.eclipse.core.runtime.compatibility@start,\
  org.eclipse.equinox.app@start,\
  org.eclipse.equinox.common@2:start,\
  org.eclipse.equinox.console@start,\
  org.eclipse.equinox.http.jetty@start,\
  org.eclipse.equinox.http.registry@start,\
  org.eclipse.equinox.http.servlet@start,\
  org.eclipse.equinox.http.servletbridge@start,\
  org.eclipse.equinox.http.servletbridge@start,\
  org.eclipse.equinox.jsp.jasper@start,\
  org.eclipse.equinox.jsp.jasper.registry@start,\
  org.eclipse.equinox.preferences@start,\
  org.eclipse.equinox.registry@start,\
  org.eclipse.equinox.security@start,\
  org.eclipse.equinox.servletbridge@start,\
  org.eclipse.equinox.servletbridge.extensionbundle@start,\
  org.eclipse.help@start,\
  org.eclipse.help.base@start,\
  org.eclipse.help.webapp@start,\
  org.eclipse.jetty.continuation@start,\
  org.eclipse.jetty.http@start,\
  org.eclipse.jetty.io@start,\
  org.eclipse.jetty.security@start,\
  org.eclipse.jetty.server@start,\
  org.eclipse.jetty.servlet@start,\
  org.eclipse.jetty.util@start,\
  org.eclipse.osgi@start,\
  org.eclipse.osgi.services@start,\
  org.eclipse.osgi.util@start,\
  org.eclipse.update.configurator@start,\
  org.hamcrest.core@start,\
  org.modelio.infocenter@start,\
