source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               e4model/,\
               .,\
               res/,\
               plugin.properties,plugin_fr.properties,\
               plugin.xml,\
               icons/,\
               images/
