<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>doc-modelio_com</artifactId>
	<packaging>pom</packaging>

	<parent>
		<groupId>org.modelio</groupId>
		<artifactId>doc-parent</artifactId>
		<version>6.2.0-SNAPSHOT</version>
		<relativePath>../../parent</relativePath>
	</parent>

	<properties>
		<outputDirectory>target/plugins</outputDirectory>
	</properties>

	<dependencies>

		<!-- MODELIO documentation EN -->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.copyright</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.analyst</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.archimate</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.modeliomodeler</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.modeliomodeler.toc</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.modeliomodeler</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.modeliomodeler.toc</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.modelioapi</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.vaudit</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.bpmn</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.metamodel.archimate</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.metamodel.analyst</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.metamodel.uml</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.workflow</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>

		<!-- MODELIO documentation FR -->
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.copyright.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.modeliomodeler.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.modeliomodeler.toc.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.analyst.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.archimate.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.modeliomodeler.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.modeliomodeler.toc.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.vaudit.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>org.modelio.documentation.bpmn.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.modelio</groupId>
			<artifactId>com.modeliosoft.modelio.documentation.workflow.nl_fr</artifactId>
			<version>6.2.0-SNAPSHOT</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>${tycho-groupid}</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho-version}</version>
				<extensions>true</extensions>
				<configuration>
					<resolver>p2</resolver>
				</configuration>
			</plugin>
			<plugin>
				<groupId>${tycho-groupid}</groupId>
				<artifactId>tycho-packaging-plugin</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<strictVersions>false</strictVersions>
					<archive>
						<!-- don't create the maven directory (descriptor files) in META-INF -->
						<addMavenDescriptor>false</addMavenDescriptor>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.8</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>initialize</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<description>Defines the list of documentation plugins to aggregate for the Modelio Web Site.</description>
</project>
