source.. = src/
output.. = bin/
javacSource = 17
javacTarget = 17
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               res/,\
               OSGI-INF/,\
               e4model/,\
               icons/,\
               plugin.properties,\
               plugin_fr.properties,\
               schema/
output.lib/ = bin/
source.res/lib/ = src/
jars.compile.order = .,\
                     lib/

