/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.math.BigInteger;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * A bendpoint type for a connection.
 *
 *
 * <p>Java class for bendpointType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="bendpointType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("bf1ea4a5-9b81-4c53-b871-a31df9112378")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bendpointType")
public class BendpointType {
    @objid ("a749ebb9-9203-4c7d-9ba9-f4877d43da80")
    @XmlAttribute(name = "x", required = true)
    protected BigInteger x;

    @objid ("9fd5e0ab-ddae-4046-804a-b0c25c5bab4b")
    @XmlAttribute(name = "y", required = true)
    protected BigInteger y;

    /**
     * Gets the value of the x property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("394024d4-9de1-40ea-b8ba-c9b4b1a05e35")
    public BigInteger getX() {
        return this.x;
    }

    /**
     * Sets the value of the x property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("2a9ba9c7-b31b-4a5d-946e-c8c74244d388")
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("70e04591-e191-4da2-9149-3c757c0436da")
    public BigInteger getY() {
        return this.y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("ca24cf6c-b68f-4e44-aa10-a9ee291c5a31")
    public void setY(BigInteger value) {
        this.y = value;
    }

}
