/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * Graphical connection type.
 *
 * If the 'relationshipref' attribute is present, the connection should reference an existing ArchiMate relationship.
 *
 * If the connection is an ArchiMate relationship type, the connection's label, documentation and properties may be determined
 * (i.e inherited) from those in the referenced ArchiMate relationship. Otherwise the connection's label, documentation and properties
 * can be provided and will be additional to (or over-ride) those contained in the referenced ArchiMate relationship.
 *
 *
 * <p>Java class for connectionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="connectionType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="label" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="documentation" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="properties" type="{http://www.opengroup.org/xsd/archimate}propertiesType" minOccurs="0"/>
 * &lt;element name="bendpoint" type="{http://www.opengroup.org/xsd/archimate}bendpointType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="style" type="{http://www.opengroup.org/xsd/archimate}styleType" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="relationshipref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("a04f6be1-3331-4ef0-b708-82c70b59741f")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectionType", propOrder = {
    "label",
    "documentation",
    "properties",
    "bendpoint",
    "style",
    "any"
})
public class ConnectionType {
    @objid ("01b2b2ee-104b-48d7-8659-ff939585b2e7")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("beb2d71e-ae02-4cf5-bbf5-95db87be03fc")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("8cbc09c0-143a-4fad-b200-1d5ea0a93ab3")
    protected List<LangStringType> label;

    @objid ("0001467b-f6d5-4b78-a658-7299bb183a56")
    protected List<LangStringType> documentation;

    @objid ("8771e5f5-cdb3-4937-beb1-f7e119686901")
    protected PropertiesType properties;

    @objid ("187e599d-d444-46c6-b5eb-3884158e1ec1")
    protected List<BendpointType> bendpoint;

    @objid ("e86b65d9-bf6d-4dfa-bdc3-dacd80fbdb73")
    protected StyleType style;

    @objid ("1a440759-6c34-4912-80a0-f5625b90fd1f")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @objid ("5f901011-6e77-4451-8bbe-bef4f68551b7")
    @XmlAttribute(name = "relationshipref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relationshipref;

    @objid ("8843bf7c-6825-4765-87f0-3cca0e80425e")
    @XmlAttribute(name = "source", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object source;

    @objid ("b3c7232f-282a-4461-8b4c-080ef5da5a1b")
    @XmlAttribute(name = "target", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object target;

    /**
     * Gets the value of the label property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getLabel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("31621d03-5269-4638-8b5d-a8fe6b031e5a")
    public List<LangStringType> getLabel() {
        if (this.label == null) {
            this.label = new ArrayList<>();
        }
        return this.label;
    }

    /**
     * Gets the value of the documentation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("33b47dda-10b5-4052-90ca-b959ffb9ef7c")
    public List<LangStringType> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("2bcad510-c8f9-40d4-80a8-50df5ad0fc5e")
    public PropertiesType getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("239e49a2-b800-43b9-ba89-9d69bf85a0b5")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the bendpoint property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bendpoint property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getBendpoint().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BendpointType }
     */
    @objid ("56aa0be3-7228-4896-88de-bd8fd91f1882")
    public List<BendpointType> getBendpoint() {
        if (this.bendpoint == null) {
            this.bendpoint = new ArrayList<>();
        }
        return this.bendpoint;
    }

    /**
     * Gets the value of the style property.
     *
     * @return possible object is
     * {@link StyleType }
     */
    @objid ("edd2c9b8-0bfa-4f63-b46f-691ba85c0936")
    public StyleType getStyle() {
        return this.style;
    }

    /**
     * Sets the value of the style property.
     *
     * @param value allowed object is
     * {@link StyleType }
     */
    @objid ("5dd2eddf-709a-4b7e-a317-e40497ac21f1")
    public void setStyle(StyleType value) {
        this.style = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("9848547b-5581-46be-ab04-6a8fbd0906e9")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("aac65357-6107-47d1-8bf4-ca8311abf198")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("5055d4f9-8f11-4f25-af93-38245a1180a3")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the relationshipref property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("ecab4f0b-d890-40ed-afca-df15ae0e02ed")
    public Object getRelationshipref() {
        return this.relationshipref;
    }

    /**
     * Sets the value of the relationshipref property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("5ba1f0e1-38ae-4bc5-990c-561e953ebe19")
    public void setRelationshipref(Object value) {
        this.relationshipref = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("98e50fb7-5634-4db2-aead-214c9bc57a23")
    public Object getSource() {
        return this.source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("fcaa2632-2b41-4220-9f26-92ca82472611")
    public void setSource(Object value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("c28f698d-8219-4d5b-9834-c19d884a94c0")
    public Object getTarget() {
        return this.target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("a6b9234c-76fe-4e61-8ee4-c89812bc6228")
    public void setTarget(Object value) {
        this.target = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("aab89b7d-aff5-4ac4-8abc-96b8ff0beea7")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
