/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for dataType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dataType">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="string"/>
 * &lt;enumeration value="boolean"/>
 * &lt;enumeration value="currency"/>
 * &lt;enumeration value="date"/>
 * &lt;enumeration value="time"/>
 * &lt;enumeration value="number"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("ddee8b1d-9d84-4a1b-8d2c-0632c76cc8f6")
@XmlType(name = "dataType")
@XmlEnum
public enum DataType {
    @objid ("2d859271-1764-4df3-a8af-64d41cd8f477")
    @XmlEnumValue("string")
    STRING("string"),
    @objid ("0717af0b-56f4-4b60-9462-e38a66ea4fa9")
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @objid ("518a7f3a-b1cf-4710-b104-882217fbd6b6")
    @XmlEnumValue("currency")
    CURRENCY("currency"),
    @objid ("e861820b-95c8-49c4-adee-e174b6bc31a2")
    @XmlEnumValue("date")
    DATE("date"),
    @objid ("1cf9b73e-ded9-4529-8831-6ab6d0234fae")
    @XmlEnumValue("time")
    TIME("time"),
    @objid ("9a5f5937-03c9-4fec-b9cc-58ef08450424")
    @XmlEnumValue("number")
    NUMBER("number");

    @objid ("8a4facda-cdb9-4f90-8b50-f1093245f317")
    private final String value;

    @objid ("4a05f9bd-7567-4ede-bcd1-5cb775fa944b")
    DataType(String v) {
        this.value = v;
    }

    @objid ("988272da-365d-4d69-a0b7-2affe0a182a1")
    public String value() {
        return this.value;
    }

    @objid ("d1c3d07b-7feb-4a61-a5d3-b465677722bd")
    public static DataType fromValue(String v) {
        for (DataType c: DataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
