/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * A base element type that can be extended by concrete ArchiMate types.
 *
 *
 * <p>Java class for elementType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="elementType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="label" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="documentation" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="properties" type="{http://www.opengroup.org/xsd/archimate}propertiesType" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("87470e7f-ed37-4577-a756-1e6097eb23d3")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementType", propOrder = {
    "label",
    "documentation",
    "properties",
    "any"
})
@XmlSeeAlso({
    Constraint.class,
    CommunicationPath.class,
    Node.class,
    Product.class,
    BusinessActor.class,
    BusinessObject.class,
    BusinessCollaboration.class,
    BusinessInteraction.class,
    WorkPackage.class,
    Goal.class,
    Stakeholder.class,
    Network.class,
    BusinessEvent.class,
    Device.class,
    ApplicationFunction.class,
    Representation.class,
    Principle.class,
    Requirement.class,
    DataObject.class,
    Gap.class,
    Value.class,
    BusinessInterface.class,
    Contract.class,
    InfrastructureFunction.class,
    ApplicationService.class,
    Deliverable.class,
    BusinessRole.class,
    Assessment.class,
    ApplicationCollaboration.class,
    SystemSoftware.class,
    Driver.class,
    InfrastructureInterface.class,
    ApplicationInterface.class,
    InfrastructureService.class,
    Junction.class,
    Plateau.class,
    ApplicationComponent.class,
    Artifact.class,
    BusinessFunction.class,
    BusinessService.class,
    ApplicationInteraction.class,
    Meaning.class,
    BusinessProcess.class,
    Location.class
})
public class ElementType {
    @objid ("9aaa827d-4db4-41dd-bb17-3e320e9e7bbe")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("81478621-465a-45a8-ab96-3ced0044b680")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("397400ef-3a4e-4790-be92-aef5cd875437")
    protected List<LangStringType> label;

    @objid ("655f630b-6811-4e97-bcf8-c0e1548a54e6")
    protected List<LangStringType> documentation;

    @objid ("0498a46b-6ee7-4254-93ef-5f376fbb11c1")
    protected PropertiesType properties;

    @objid ("35d343cd-1c10-46a4-83fc-134bade69508")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the label property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getLabel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("5657667e-3f58-4a4b-8b3c-e38a028ee55d")
    public List<LangStringType> getLabel() {
        if (this.label == null) {
            this.label = new ArrayList<>();
        }
        return this.label;
    }

    /**
     * Gets the value of the documentation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("41af36f9-2c4c-4de3-a2be-9391362a3250")
    public List<LangStringType> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("a0642db8-023f-4e36-ba89-b1e2b00ad1a7")
    public PropertiesType getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("4d32b77c-5d93-4763-9571-434901646e81")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("63075bf3-4729-48c4-b74b-d33f48ef36fe")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("e22ef981-3ea8-4a21-b101-7bf26c62ef13")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("62e4e07f-fea3-403d-8a47-fc10f4b6d78b")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("b21e0e1d-5a17-4ef8-90ed-627e1f932f63")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
