/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.math.BigDecimal;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Font type.
 *
 *
 * <p>Java class for fontType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="fontType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="color" type="{http://www.opengroup.org/xsd/archimate}rgbColorType" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 * &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("7cb34b93-2b9c-4a02-b15b-53046f05d930")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fontType", propOrder = {
    "color"
})
public class FontType {
    @objid ("8f1cd1a4-2e14-437e-ab3c-a23f28b0be63")
    @XmlAttribute(name = "name")
    protected String name;

    @objid ("6a02b170-2db8-48d4-9314-38965eb81f92")
    @XmlAttribute(name = "style")
    protected String style;

    @objid ("5e66370d-620b-405b-adef-cfbe2a0d157e")
    protected RgbColorType color;

    @objid ("70dfde6a-e6cb-48ff-889e-d328546c46ed")
    @XmlAttribute(name = "size")
    protected BigDecimal size;

    /**
     * Gets the value of the color property.
     *
     * @return possible object is
     * {@link RgbColorType }
     */
    @objid ("a037f08d-1c70-4655-96e1-73613015a9e2")
    public RgbColorType getColor() {
        return this.color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value allowed object is
     * {@link RgbColorType }
     */
    @objid ("1dca015a-6eea-4407-b272-fc22f6221e6b")
    public void setColor(RgbColorType value) {
        this.color = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("2d390ee4-c84b-4f48-b83e-cd9aabc78d1c")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("e81f998d-9164-4ff6-a076-173c3bdc1f15")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the size property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    @objid ("0be8ac1d-ffbb-4386-9aba-06e5f3cb6098")
    public BigDecimal getSize() {
        return this.size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value allowed object is
     * {@link BigDecimal }
     */
    @objid ("2cc5c756-494e-4a0c-94c4-84a3c0c4b6f0")
    public void setSize(BigDecimal value) {
        this.size = value;
    }

    /**
     * Gets the value of the style property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("bb0172bd-559a-4c1e-a0e1-94afcc2f936a")
    public String getStyle() {
        return this.style;
    }

    /**
     * Sets the value of the style property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("c3f39d47-a795-4457-a963-1b69f79c9504")
    public void setStyle(String value) {
        this.style = value;
    }

}
