/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * A base string type for multi-language strings.
 *
 *
 * <p>Java class for langStringType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="langStringType">
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("ff7dea77-f950-445b-9d73-08c51fa09ff8")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "langStringType", propOrder = {
    "value"
})
public class LangStringType {
    @objid ("5978cffa-3b3c-4acf-b1ec-646325decd99")
    @XmlValue
    protected String value;

    @objid ("b08c96a3-4c6c-495e-b7d8-e508179be7b2")
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("01574de2-adf8-4eec-811d-4ab40c990158")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("63090b59-3586-471d-ac68-6f6b4da0e8d8")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("d1b4ea5c-4c78-48aa-bbbb-82dd8492a3fb")
    public String getLang() {
        return this.lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("4a737e39-50c0-4dc3-8b6c-7fb551a1e92b")
    public void setLang(String value) {
        this.lang = value;
    }

}
