/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This is the root model element.
 * It is a container for the elements, relationships, diagrams and organisations of the model.
 *
 * The "metadata" element is the optional metadata for the model.
 * The "name" element is the name of the model.
 * The "documentation" element is for the documentation of the model.
 * The "properties" element is optional and is for any property instance of the model.
 * The "elements" element is mandatory and is a container for all elements.
 * The "relationships" element is optional and is a container for any relationships.
 * The "organization" element is optional and is a container for structural organisation of model elements and relationships.
 * The "propertydefs" element is optional and is a container for any property definitions.
 * The "views" element is optional and is a container for any Views.
 *
 *
 * <p>Java class for modelType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="modelType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="metadata" type="{http://www.opengroup.org/xsd/archimate}MetadataType" minOccurs="0"/>
 * &lt;element name="name" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="documentation" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="properties" type="{http://www.opengroup.org/xsd/archimate}propertiesType" minOccurs="0"/>
 * &lt;element name="elements" type="{http://www.opengroup.org/xsd/archimate}elementsType"/>
 * &lt;element name="relationships" type="{http://www.opengroup.org/xsd/archimate}relationshipsType" minOccurs="0"/>
 * &lt;element name="organization" type="{http://www.opengroup.org/xsd/archimate}organizationType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="propertydefs" type="{http://www.opengroup.org/xsd/archimate}propertiesDefinitionsType" minOccurs="0"/>
 * &lt;element name="views" type="{http://www.opengroup.org/xsd/archimate}viewsType" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("b3617bbf-f1b7-4039-a004-678c7310662d")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelType", propOrder = {
    "metadata",
    "name",
    "documentation",
    "properties",
    "elements",
    "relationships",
    "organization",
    "propertydefs",
    "views",
    "any"
})
@XmlRootElement(name = "model", namespace = "http://www.opengroup.org/xsd/archimate")
public class ModelType {
    @objid ("8f7701dc-67b8-44a7-afdc-32c865f3824c")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("ee8087ac-ba3b-498b-9afe-1b0f7be75add")
    @XmlAttribute(name = "version")
    protected String version;

    @objid ("427d615f-b7d2-4fed-8519-8fe6d892b7ce")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("ab9a75fb-247e-4643-978c-51c6040c9e07")
    protected MetadataType metadata;

    @objid ("cc3fd118-a31e-41d2-956a-20792af76f3e")
    protected List<LangStringType> name;

    @objid ("dfb1a9a0-a09f-4227-b15a-ff2e511d2c81")
    protected List<LangStringType> documentation;

    @objid ("c77199ae-513a-4531-82de-d76936e9dad5")
    protected PropertiesType properties;

    @objid ("46ed4148-ba02-4f0f-a404-0ec4813a8f4e")
    @XmlElement(required = true)
    protected ElementsType elements;

    @objid ("d7de81f4-0bd9-4df6-a8d5-4013680c5ad7")
    protected RelationshipsType relationships;

    @objid ("f7695f80-92ad-4632-9c55-0b4a3e7c6e00")
    protected List<OrganizationType> organization;

    @objid ("d6119ed3-186a-4838-9208-380a83427e8f")
    protected PropertiesDefinitionsType propertydefs;

    @objid ("44254a03-6c11-433c-97b5-12054259ed9e")
    protected ViewsType views;

    @objid ("74efc250-bfd1-4f7e-97fa-a59e360c3ad8")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the metadata property.
     *
     * @return possible object is
     * {@link MetadataType }
     */
    @objid ("8be42f97-53d8-44b9-927d-f93e65c4910a")
    public MetadataType getMetadata() {
        return this.metadata;
    }

    /**
     * Sets the value of the metadata property.
     *
     * @param value allowed object is
     * {@link MetadataType }
     */
    @objid ("0e621106-3884-46d4-8738-ba9d7ed8f909")
    public void setMetadata(MetadataType value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the name property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("1f584281-2392-4dc8-abaf-d41b1bc561b8")
    public List<LangStringType> getName() {
        if (this.name == null) {
            this.name = new ArrayList<>();
        }
        return this.name;
    }

    /**
     * Gets the value of the documentation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("ce122a4a-f34d-46f6-8d20-4827b87c43ff")
    public List<LangStringType> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("7717e1d0-ae28-4ef6-89cd-c57dc5620844")
    public PropertiesType getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("3a275e6e-5116-400b-b521-854b6e21860b")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the elements property.
     *
     * @return possible object is
     * {@link ElementsType }
     */
    @objid ("1423ea15-6878-40c0-89d4-33c85f24d09b")
    public ElementsType getElements() {
        return this.elements;
    }

    /**
     * Sets the value of the elements property.
     *
     * @param value allowed object is
     * {@link ElementsType }
     */
    @objid ("027253d3-a6f5-41a1-84c3-7f53c7dc0561")
    public void setElements(ElementsType value) {
        this.elements = value;
    }

    /**
     * Gets the value of the relationships property.
     *
     * @return possible object is
     * {@link RelationshipsType }
     */
    @objid ("fbcb6ff3-1075-4bfe-9236-e77bffd13b4b")
    public RelationshipsType getRelationships() {
        return this.relationships;
    }

    /**
     * Sets the value of the relationships property.
     *
     * @param value allowed object is
     * {@link RelationshipsType }
     */
    @objid ("5871217c-c4e9-409f-bce3-936cc6b9e3a0")
    public void setRelationships(RelationshipsType value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the organization property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organization property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganization().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationType }
     */
    @objid ("6756dff5-41bf-4c56-9f5e-f980c49cd04d")
    public List<OrganizationType> getOrganization() {
        if (this.organization == null) {
            this.organization = new ArrayList<>();
        }
        return this.organization;
    }

    /**
     * Gets the value of the propertydefs property.
     *
     * @return possible object is
     * {@link PropertiesDefinitionsType }
     */
    @objid ("900d8da4-8082-42ac-a618-613bbdd94b9b")
    public PropertiesDefinitionsType getPropertydefs() {
        return this.propertydefs;
    }

    /**
     * Sets the value of the propertydefs property.
     *
     * @param value allowed object is
     * {@link PropertiesDefinitionsType }
     */
    @objid ("b0f56388-ec7e-40f6-91a5-e9c91e434568")
    public void setPropertydefs(PropertiesDefinitionsType value) {
        this.propertydefs = value;
    }

    /**
     * Gets the value of the views property.
     *
     * @return possible object is
     * {@link ViewsType }
     */
    @objid ("e9ec1c19-b44b-4922-a90d-38dbd774523d")
    public ViewsType getViews() {
        return this.views;
    }

    /**
     * Sets the value of the views property.
     *
     * @param value allowed object is
     * {@link ViewsType }
     */
    @objid ("b8f99db0-73ab-4494-be9e-84cf11911d3b")
    public void setViews(ViewsType value) {
        this.views = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("3ca3bda7-3fae-46a0-9d8d-35a03277821d")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("fa3f350d-a3d0-4c99-9ab8-625393d412b6")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("3996c860-75f1-43a6-a1c6-c91e5145da93")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("22f05a1d-7758-4b3c-8014-1d42d9be4f0a")
    public String getVersion() {
        return this.version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("c934857b-4a79-4d9f-a4ed-503091df240f")
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("a0ea5a7a-e4d1-4247-8e08-cc83123908a4")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
