/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * Graphical node type. It can contain child node types.
 *
 * If the 'elementref' attribute is present, it should reference an existing ArchiMate element.
 *
 * If the node is an ArchiMate element type, the node's label, documentation and properties may be determined
 * (i.e inherited) from those in the referenced ArchiMate element. Otherwise the node's label, documentation and properties
 * can be provided and will be additional to (or over-ride) those contained in the referenced ArchiMate element.
 *
 *
 * <p>Java class for nodeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="nodeType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="label" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="documentation" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="properties" type="{http://www.opengroup.org/xsd/archimate}propertiesType" minOccurs="0"/>
 * &lt;element name="style" type="{http://www.opengroup.org/xsd/archimate}styleType" minOccurs="0"/>
 * &lt;element name="node" type="{http://www.opengroup.org/xsd/archimate}nodeType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="elementref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;attribute name="w" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;attribute name="h" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("c9a31a8d-f59f-4eab-8168-c659d79e1621")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nodeType", propOrder = {
    "label",
    "documentation",
    "properties",
    "style",
    "node",
    "any"
})
public class NodeType {
    @objid ("c8c739df-525a-4967-ae7e-d06a403ab4a2")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("df8d01d2-c9b8-4131-9ca7-45c84978542e")
    @XmlAttribute(name = "type")
    protected String type;

    @objid ("7e991ffd-3f46-4a72-b137-c7de254d7fc6")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("1c6aed16-5d46-4f98-bd17-2db3c0d0f86c")
    protected List<LangStringType> label;

    @objid ("3543a9c3-b2b0-4657-ba57-19da31d5a6e0")
    protected List<LangStringType> documentation;

    @objid ("fa76432f-13ae-4864-983b-8d73a06541ed")
    protected PropertiesType properties;

    @objid ("2cd469e1-4602-4faa-98ac-313e684839e3")
    protected StyleType style;

    @objid ("48da5b39-bda0-4500-a9a0-b1d9f8b60d39")
    protected List<NodeType> node;

    @objid ("a4bce3d1-a602-49dd-b997-58cfee41abb2")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @objid ("3a2c2b8c-4fae-4bd8-bfa4-6d0a1bf4179c")
    @XmlAttribute(name = "elementref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object elementref;

    @objid ("3b7b63c2-ef6c-4397-b091-57e6811dd03c")
    @XmlAttribute(name = "x", required = true)
    protected BigInteger x;

    @objid ("e913123c-f480-4be2-8eb8-0f846c86b428")
    @XmlAttribute(name = "y", required = true)
    protected BigInteger y;

    @objid ("75132528-e1e5-4226-bed4-8cf981586c1d")
    @XmlAttribute(name = "w", required = true)
    protected BigInteger w;

    @objid ("0d29f72e-64b7-4ea9-99b8-d305a54d3631")
    @XmlAttribute(name = "h", required = true)
    protected BigInteger h;

    /**
     * Gets the value of the label property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getLabel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("debff1a4-b484-4b52-ac1b-f33d60f3ea73")
    public List<LangStringType> getLabel() {
        if (this.label == null) {
            this.label = new ArrayList<>();
        }
        return this.label;
    }

    /**
     * Gets the value of the documentation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("74e72505-c3f6-459e-9555-6fe4b79718ae")
    public List<LangStringType> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("34197d84-61d7-4a01-8886-370697bad9e4")
    public PropertiesType getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("ff4f5e34-5cde-4ba0-8cfb-457922d4c67b")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the style property.
     *
     * @return possible object is
     * {@link StyleType }
     */
    @objid ("dd2c3bb6-f5dd-47e2-ade6-2ac251694e9f")
    public StyleType getStyle() {
        return this.style;
    }

    /**
     * Sets the value of the style property.
     *
     * @param value allowed object is
     * {@link StyleType }
     */
    @objid ("20d58a21-fdc5-482d-9ca4-394fdf06ad83")
    public void setStyle(StyleType value) {
        this.style = value;
    }

    /**
     * Gets the value of the node property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getNode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeType }
     */
    @objid ("d89a15be-7e6e-4ec2-8dd5-7d5675467069")
    public List<NodeType> getNode() {
        if (this.node == null) {
            this.node = new ArrayList<>();
        }
        return this.node;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("b0539b3f-4cd2-4d64-9bbd-407872481fae")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("abdb24ae-91e2-4259-a742-8c0f9d9bbdb3")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("06661266-a830-4306-94ad-51f61b8984a4")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the elementref property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("d4e75559-fcbb-4cd9-b496-c19aea7ea5e0")
    public Object getElementref() {
        return this.elementref;
    }

    /**
     * Sets the value of the elementref property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("a10573e1-d235-4e0d-a68c-74a09a936c8f")
    public void setElementref(Object value) {
        this.elementref = value;
    }

    /**
     * Gets the value of the x property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("c2b423fd-a5f4-42ac-9205-64bf66bc61dc")
    public BigInteger getX() {
        return this.x;
    }

    /**
     * Sets the value of the x property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("f7b51fd9-f90e-4de7-ab8f-139dd29696c5")
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("70c99d80-7c29-4e00-b2d0-83b5f2d45a77")
    public BigInteger getY() {
        return this.y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("99c117db-d966-4095-9915-a6886b1152d3")
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the w property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("440fc244-c738-4a2a-ac02-a8e97529ec3c")
    public BigInteger getW() {
        return this.w;
    }

    /**
     * Sets the value of the w property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("d4cb72e3-da55-497e-bca3-bb801b96730a")
    public void setW(BigInteger value) {
        this.w = value;
    }

    /**
     * Gets the value of the h property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("f22e01d5-0294-4dcb-b74d-f00bc8d74e76")
    public BigInteger getH() {
        return this.h;
    }

    /**
     * Sets the value of the h property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("402a5775-d348-483e-b71c-fa083a2a9e39")
    public void setH(BigInteger value) {
        this.h = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("39c32955-57a8-4ae9-8079-9ca5f01d9241")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("108a3cb0-d5fc-44ea-b92f-fe461e7c5115")
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("af890057-5b1a-4edc-9834-a40bb191479a")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
