/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.modelio.archimate.exchange.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@objid ("8b868db2-1dd5-417a-8d24-9880cf23df4b")
@XmlRegistry
public class ObjectFactory {
    @objid ("5d3f7a45-9b75-4239-a2ba-52b28ed79b30")
    private static final QName _Model_QNAME = new QName("http://www.opengroup.org/xsd/archimate", "model");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.modelio.archimate.exchange.model
     */
    @objid ("5b60ce28-2171-444a-a7f8-64ef07df2e2e")
    public ObjectFactory() {

    }

    /**
     * Create an instance of {@link ModelType }
     */
    @objid ("9ce92139-6395-4cf4-bf2a-5b706eeb1d9b")
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link ViewsType }
     */
    @objid ("05937dbc-4b5e-4a4e-a0ce-891817bd5ac9")
    public ViewsType createViewsType() {
        return new ViewsType();
    }

    /**
     * Create an instance of {@link RealisationRelationship }
     */
    @objid ("c0d6340c-45ca-40b6-bb9c-c179a5b5f7ba")
    public RealisationRelationship createRealisationRelationship() {
        return new RealisationRelationship();
    }

    /**
     * Create an instance of {@link Constraint }
     */
    @objid ("0292e2db-f701-4765-9326-f5bc58e97394")
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link CommunicationPath }
     */
    @objid ("3c94674c-7a34-4005-a503-eec0ec31dc0e")
    public CommunicationPath createCommunicationPath() {
        return new CommunicationPath();
    }

    /**
     * Create an instance of {@link Node }
     */
    @objid ("12bd1edd-85e2-4a92-a764-a848860d3d44")
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Product }
     */
    @objid ("66662321-a86d-4f70-a465-1074255f0b1f")
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link BusinessActor }
     */
    @objid ("70b2fedf-44de-4bda-b383-f317d7a1d246")
    public BusinessActor createBusinessActor() {
        return new BusinessActor();
    }

    /**
     * Create an instance of {@link BusinessObject }
     */
    @objid ("56880960-fd45-4e26-b9d4-ffae63825093")
    public BusinessObject createBusinessObject() {
        return new BusinessObject();
    }

    /**
     * Create an instance of {@link ConnectionType }
     */
    @objid ("d17e2d09-a013-45c4-9983-c0d3f082d802")
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link BusinessCollaboration }
     */
    @objid ("4ebeab1f-4841-49bf-a4a5-9e2bfd72a752")
    public BusinessCollaboration createBusinessCollaboration() {
        return new BusinessCollaboration();
    }

    /**
     * Create an instance of {@link BusinessInteraction }
     */
    @objid ("23c6d7be-223c-4d78-985d-6cec4e0c3a35")
    public BusinessInteraction createBusinessInteraction() {
        return new BusinessInteraction();
    }

    /**
     * Create an instance of {@link WorkPackage }
     */
    @objid ("f47dedac-ce6e-4d88-b01b-296ab56dfbbd")
    public WorkPackage createWorkPackage() {
        return new WorkPackage();
    }

    /**
     * Create an instance of {@link StyleType }
     */
    @objid ("8d1ab7cf-02ef-4dcf-ad09-c61a481e9ca7")
    public StyleType createStyleType() {
        return new StyleType();
    }

    /**
     * Create an instance of {@link Goal }
     */
    @objid ("b5243159-e28f-45dc-b39a-c366db9e1caf")
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link AggregationRelationship }
     */
    @objid ("ea34cf02-fe2e-4c76-80e6-409ecc4badb1")
    public AggregationRelationship createAggregationRelationship() {
        return new AggregationRelationship();
    }

    /**
     * Create an instance of {@link Stakeholder }
     */
    @objid ("69e5cdec-2a49-42c7-8ed5-f4102fa3d226")
    public Stakeholder createStakeholder() {
        return new Stakeholder();
    }

    /**
     * Create an instance of {@link FlowRelationship }
     */
    @objid ("7509509a-9c5b-4765-98ed-a1b0e559575a")
    public FlowRelationship createFlowRelationship() {
        return new FlowRelationship();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     */
    @objid ("1e409b20-cca3-46a1-bff8-42cfe76e67c4")
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link Network }
     */
    @objid ("12113c69-5568-44d0-998f-1a3b4f45186f")
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link InfluenceRelationship }
     */
    @objid ("d2a71575-0bbc-4371-a257-57230f88a46f")
    public InfluenceRelationship createInfluenceRelationship() {
        return new InfluenceRelationship();
    }

    /**
     * Create an instance of {@link UsedByRelationship }
     */
    @objid ("431a12c5-8abc-48fb-86fe-986cd06e5e49")
    public UsedByRelationship createUsedByRelationship() {
        return new UsedByRelationship();
    }

    /**
     * Create an instance of {@link BusinessEvent }
     */
    @objid ("99f5f7a7-68cf-49d9-8b96-7c9140da16ae")
    public BusinessEvent createBusinessEvent() {
        return new BusinessEvent();
    }

    /**
     * Create an instance of {@link BendpointType }
     */
    @objid ("4049c061-c9fc-40ec-8790-e5d2476a104c")
    public BendpointType createBendpointType() {
        return new BendpointType();
    }

    /**
     * Create an instance of {@link Device }
     */
    @objid ("b2c6e3aa-0af8-4935-8098-cbc3385b1983")
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link ApplicationFunction }
     */
    @objid ("3d0a6047-59d6-4a37-b9e2-096a7703beb7")
    public ApplicationFunction createApplicationFunction() {
        return new ApplicationFunction();
    }

    /**
     * Create an instance of {@link MetadataType }
     */
    @objid ("f41fea92-3e7f-4358-baa7-aa9d9dc32107")
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link Representation }
     */
    @objid ("25b04c65-2323-4ed9-81e0-3a3e1e29eee6")
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link Principle }
     */
    @objid ("e131d9fe-7046-42ab-9d47-2e6f06bda1ac")
    public Principle createPrinciple() {
        return new Principle();
    }

    /**
     * Create an instance of {@link NodeType }
     */
    @objid ("6536c70b-c2aa-42b1-a36e-1bf1510bd3b7")
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link ElementsType }
     */
    @objid ("ab35f8d2-d25a-4d96-9a78-7aa83908e286")
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link Requirement }
     */
    @objid ("3b6bf8ce-c88a-472c-b912-2239748ae033")
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link RgbColorType }
     */
    @objid ("2dd4038c-042b-47cd-b13a-541cc3a27d9e")
    public RgbColorType createRgbColorType() {
        return new RgbColorType();
    }

    /**
     * Create an instance of {@link AssignmentRelationship }
     */
    @objid ("ac34e991-6a48-4322-802d-29cb89eea279")
    public AssignmentRelationship createAssignmentRelationship() {
        return new AssignmentRelationship();
    }

    /**
     * Create an instance of {@link DataObject }
     */
    @objid ("168a6ae4-660d-4cdc-95f0-4a8e70913409")
    public DataObject createDataObject() {
        return new DataObject();
    }

    /**
     * Create an instance of {@link Gap }
     */
    @objid ("acd74941-8753-45e1-856a-3d0dd3672600")
    public Gap createGap() {
        return new Gap();
    }

    /**
     * Create an instance of {@link Value }
     */
    @objid ("6002af64-94e9-4a2a-a7f4-a608d66687cf")
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link PropertiesType }
     */
    @objid ("4118bb67-4159-424f-9640-606fc8c038fd")
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link ViewType }
     */
    @objid ("a28724fc-c527-4877-9e0b-2554145fae44")
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link BusinessInterface }
     */
    @objid ("4cad804c-1b81-4188-b8df-f9bd31452799")
    public BusinessInterface createBusinessInterface() {
        return new BusinessInterface();
    }

    /**
     * Create an instance of {@link Contract }
     */
    @objid ("ceb3cf70-f6ef-43b2-9f52-2ed35e0bd5bc")
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link InfrastructureFunction }
     */
    @objid ("c6d04767-86f4-426c-8302-0cb5093450e1")
    public InfrastructureFunction createInfrastructureFunction() {
        return new InfrastructureFunction();
    }

    /**
     * Create an instance of {@link AccessRelationship }
     */
    @objid ("4ad35cfa-f36c-4cd9-878b-bd3d4890085e")
    public AccessRelationship createAccessRelationship() {
        return new AccessRelationship();
    }

    /**
     * Create an instance of {@link ApplicationService }
     */
    @objid ("2953bffc-57ad-4b6d-b9ae-e47e577eabd4")
    public ApplicationService createApplicationService() {
        return new ApplicationService();
    }

    /**
     * Create an instance of {@link Deliverable }
     */
    @objid ("b27b619d-8b0d-4e93-a8cf-9e86d8465a62")
    public Deliverable createDeliverable() {
        return new Deliverable();
    }

    /**
     * Create an instance of {@link ItemType }
     */
    @objid ("0335b7c7-222e-44dc-b963-13d6fd9baf87")
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link BusinessRole }
     */
    @objid ("b4b8734e-849b-4160-bb5a-436edc6e1cfe")
    public BusinessRole createBusinessRole() {
        return new BusinessRole();
    }

    /**
     * Create an instance of {@link Assessment }
     */
    @objid ("f0dd85c1-d7b3-4435-b4ab-11878e90ae31")
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link ApplicationCollaboration }
     */
    @objid ("44f7e2f5-6bcf-4a55-8f96-927a8e8484ef")
    public ApplicationCollaboration createApplicationCollaboration() {
        return new ApplicationCollaboration();
    }

    /**
     * Create an instance of {@link SystemSoftware }
     */
    @objid ("362fd108-6b43-445c-8394-ad305b891a58")
    public SystemSoftware createSystemSoftware() {
        return new SystemSoftware();
    }

    /**
     * Create an instance of {@link Driver }
     */
    @objid ("79aad391-c31a-4f10-9735-48a9124938e9")
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link InfrastructureInterface }
     */
    @objid ("8d5fca69-fff9-4553-b0fc-dd266697a507")
    public InfrastructureInterface createInfrastructureInterface() {
        return new InfrastructureInterface();
    }

    /**
     * Create an instance of {@link PropertiesDefinitionsType }
     */
    @objid ("d2964be1-afdf-4297-a48a-be0fc4d794f4")
    public PropertiesDefinitionsType createPropertiesDefinitionsType() {
        return new PropertiesDefinitionsType();
    }

    /**
     * Create an instance of {@link SpecialisationRelationship }
     */
    @objid ("105fbdc3-91ad-400b-bc9f-6cf1e5af3a88")
    public SpecialisationRelationship createSpecialisationRelationship() {
        return new SpecialisationRelationship();
    }

    /**
     * Create an instance of {@link PropertyType }
     */
    @objid ("d1e1eecd-91ea-4984-86d3-bdf391abe6f2")
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link ApplicationInterface }
     */
    @objid ("1e23ad6d-cdff-4c2a-bc1e-10ce9db0e1ca")
    public ApplicationInterface createApplicationInterface() {
        return new ApplicationInterface();
    }

    /**
     * Create an instance of {@link AssociationRelationship }
     */
    @objid ("093e32d5-1939-49d4-abff-30f84b50c35d")
    public AssociationRelationship createAssociationRelationship() {
        return new AssociationRelationship();
    }

    /**
     * Create an instance of {@link InfrastructureService }
     */
    @objid ("bc9ee236-ef92-48b0-8421-e6d640365b25")
    public InfrastructureService createInfrastructureService() {
        return new InfrastructureService();
    }

    /**
     * Create an instance of {@link Junction }
     */
    @objid ("a2c64745-6b96-4da3-8643-b91f09be73b0")
    public Junction createJunction() {
        return new Junction();
    }

    /**
     * Create an instance of {@link CompositionRelationship }
     */
    @objid ("43bcfae6-8651-47ac-ae24-b3c4cdbaad7b")
    public CompositionRelationship createCompositionRelationship() {
        return new CompositionRelationship();
    }

    /**
     * Create an instance of {@link PropertyDefinitionType }
     */
    @objid ("4dc11515-6133-43cd-9f8c-469c369a6432")
    public PropertyDefinitionType createPropertyDefinitionType() {
        return new PropertyDefinitionType();
    }

    /**
     * Create an instance of {@link Plateau }
     */
    @objid ("ee3c39c9-25d9-4bc5-bfe9-b6ecb66ac0ac")
    public Plateau createPlateau() {
        return new Plateau();
    }

    /**
     * Create an instance of {@link FontType }
     */
    @objid ("eb04669e-c130-49c9-bdd7-a16ea8fc06e1")
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     */
    @objid ("a184a8cf-0e46-44de-9226-5d049039861b")
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link ApplicationComponent }
     */
    @objid ("0a8e4394-0b38-4793-acf2-467b3c5c5943")
    public ApplicationComponent createApplicationComponent() {
        return new ApplicationComponent();
    }

    /**
     * Create an instance of {@link LangStringType }
     */
    @objid ("336004c5-5c24-4275-8a2f-4bf8143a1981")
    public LangStringType createLangStringType() {
        return new LangStringType();
    }

    /**
     * Create an instance of {@link TriggeringRelationship }
     */
    @objid ("9384ea77-bb5e-49f4-b38f-786e94e724f5")
    public TriggeringRelationship createTriggeringRelationship() {
        return new TriggeringRelationship();
    }

    /**
     * Create an instance of {@link Artifact }
     */
    @objid ("e8e3fc26-fc98-4610-9974-be4fd877ae5f")
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link BusinessFunction }
     */
    @objid ("6bc8a9e5-cd29-4ad2-b038-511e2249a3a3")
    public BusinessFunction createBusinessFunction() {
        return new BusinessFunction();
    }

    /**
     * Create an instance of {@link OrganizationType }
     */
    @objid ("50394aa8-6ccf-46f2-b28c-f37f78b84bd8")
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link BusinessService }
     */
    @objid ("342fabb6-ace9-4d2f-9bd1-808cfac3e1cb")
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ApplicationInteraction }
     */
    @objid ("54eab849-2bcd-4b3f-8325-96dddc5ec888")
    public ApplicationInteraction createApplicationInteraction() {
        return new ApplicationInteraction();
    }

    /**
     * Create an instance of {@link ElementType }
     */
    @objid ("87e2c301-9d8b-4d0f-b7e4-0386223bfa39")
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link Meaning }
     */
    @objid ("952b70a6-8d2c-4022-8c35-0d32ba5e7312")
    public Meaning createMeaning() {
        return new Meaning();
    }

    /**
     * Create an instance of {@link BusinessProcess }
     */
    @objid ("a901ce54-c22d-41d8-85c8-8e44c736acbc")
    public BusinessProcess createBusinessProcess() {
        return new BusinessProcess();
    }

    /**
     * Create an instance of {@link Location }
     */
    @objid ("355d95d2-8180-4b01-a302-bc571bbfd2fd")
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}}
     */
    @objid ("b21be512-ed2b-4219-8afe-2ea453ece130")
    @XmlElementDecl(namespace = "http://www.opengroup.org/xsd/archimate", name = "model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<>(_Model_QNAME, ModelType.class, null, value);
    }

}
