/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * A Property definition type containing its unique identifier, name, and data type.
 *
 *
 * <p>Java class for propertyDefinitionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="propertyDefinitionType">
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="type" use="required" type="{http://www.opengroup.org/xsd/archimate}dataType" />
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("d2aaaf2e-2fa5-4f47-bfac-4bb37cb2f583")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertyDefinitionType", propOrder = {
    "value"
})
public class PropertyDefinitionType {
    @objid ("d9fdb7f5-7143-41d4-bae3-5af566585b6a")
    @XmlValue
    protected String value;

    @objid ("6a2b0b8b-7fd8-49dd-acfc-9fa3d81924ed")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("6652aa0c-14af-4f46-917d-c62bb939fa01")
    @XmlAttribute(name = "name", required = true)
    protected String name;

    @objid ("74b7eb28-22fa-49a7-819d-5b3afc8fade3")
    @XmlAttribute(name = "type", required = true)
    protected DataType type;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("10099c47-f65d-4dad-a21f-d995ce5f7fdb")
    public String getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("8dfd3396-9ac2-4d42-8636-574ed6cf3ed6")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("1a4fcb15-09f9-4522-a858-1fb779c729c8")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("b6b3a478-1f31-46b4-b1bf-5c7923caa1da")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("fa98eb1f-4628-44f3-a80c-5cad06e22dd7")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("6117e0e1-d485-4407-9595-d67746cbcfae")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link DataType }
     */
    @objid ("56c3874d-7bc6-4b5e-be91-7048896f2964")
    public DataType getType() {
        return this.type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     * {@link DataType }
     */
    @objid ("047a8828-9d8a-4284-abd8-245101aedf43")
    public void setType(DataType value) {
        this.type = value;
    }

}
