/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * This is a container for all the Property definition types used globally in the model.
 *
 *
 * <p>Java class for propertiesDefinitionsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="propertiesDefinitionsType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="propertydef" type="{http://www.opengroup.org/xsd/archimate}propertyDefinitionType" maxOccurs="unbounded"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("29a15829-41f7-4315-8192-a28c55f43cbf")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesDefinitionsType", propOrder = {
    "propertydef"
})
public class PropertiesDefinitionsType {
    @objid ("94202bcf-b4a1-43f4-8efe-99fe2f6db4fe")
    @XmlElement(required = true)
    protected List<PropertyDefinitionType> propertydef;

    /**
     * Gets the value of the propertydef property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertydef property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getPropertydef().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyDefinitionType }
     */
    @objid ("b66d22b3-bfcf-4e31-a7db-2e24cab689a9")
    public List<PropertyDefinitionType> getPropertydef() {
        if (this.propertydef == null) {
            this.propertydef = new ArrayList<>();
        }
        return this.propertydef;
    }

}
