/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * A base relationship type that can be extended by concrete ArchiMate types.
 *
 *
 * <p>Java class for relationshipType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="relationshipType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="label" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="documentation" type="{http://www.opengroup.org/xsd/archimate}langStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="properties" type="{http://www.opengroup.org/xsd/archimate}propertiesType" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 * &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("19d94fe4-651a-4ab3-b676-71e3f58fd549")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipType", propOrder = {
    "label",
    "documentation",
    "properties",
    "any"
})
@XmlSeeAlso({
    RealisationRelationship.class,
    AggregationRelationship.class,
    FlowRelationship.class,
    InfluenceRelationship.class,
    UsedByRelationship.class,
    AssignmentRelationship.class,
    AccessRelationship.class,
    SpecialisationRelationship.class,
    AssociationRelationship.class,
    CompositionRelationship.class,
    TriggeringRelationship.class
})
public class RelationshipType {
    @objid ("4efc4fd0-048e-487f-a574-4826eb175c98")
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @objid ("77934b43-f460-4526-9775-6ffade1fa9c1")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("d14b8c0d-1055-467a-9038-7975a40ff613")
    protected List<LangStringType> label;

    @objid ("e853cd7c-ce0c-40b7-8c15-74aa257d120e")
    protected List<LangStringType> documentation;

    @objid ("b31d7ef3-bb75-44f2-9e71-7059c1cea630")
    protected PropertiesType properties;

    @objid ("7619c94b-5ebe-4cca-bef6-9cc12c3b8172")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @objid ("ed218c78-87ec-4921-b48d-4d6674ba17a5")
    @XmlAttribute(name = "source", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object source;

    @objid ("e2488a8d-deef-446f-a5bd-0165bf770bbd")
    @XmlAttribute(name = "target", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object target;

    /**
     * Gets the value of the label property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getLabel().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("20dbfbb9-02b6-4705-9689-21b0be919783")
    public List<LangStringType> getLabel() {
        if (this.label == null) {
            this.label = new ArrayList<>();
        }
        return this.label;
    }

    /**
     * Gets the value of the documentation property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getDocumentation().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LangStringType }
     */
    @objid ("0dcee3af-dfc2-42cd-a981-6ee4c9373276")
    public List<LangStringType> getDocumentation() {
        if (this.documentation == null) {
            this.documentation = new ArrayList<>();
        }
        return this.documentation;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    @objid ("571d1b1e-23f1-403d-8e56-8493edcadc9a")
    public PropertiesType getProperties() {
        return this.properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     * {@link PropertiesType }
     */
    @objid ("d0b0c018-d586-49d5-8f3e-6af4d3250754")
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("baaf2622-86eb-4f97-a995-83b3f7418d03")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    @objid ("561aafe5-e7f2-4a07-a06f-7a3bd6b37530")
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     * {@link String }
     */
    @objid ("3f947c4b-b6ca-4e01-a7ca-d959eb187e77")
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("5661cfa9-64b0-4c89-b60f-6ca37044519d")
    public Object getSource() {
        return this.source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("9ed4fce2-14fc-4e85-9862-63fcc66c77b2")
    public void setSource(Object value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is
     * {@link Object }
     */
    @objid ("28ab4ec4-e06a-48fb-bc85-96b65e06a2f8")
    public Object getTarget() {
        return this.target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is
     * {@link Object }
     */
    @objid ("337917e5-7d9d-4c27-b0b3-4d2b76769b7b")
    public void setTarget(Object value) {
        this.target = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("ede717b4-a3c8-4cd2-8635-de3d06a01ce9")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
