/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

/**
 * RGB Color type.
 * The r, g, b attributes range from 0 - 255.
 * The a (alpha) transparency attribute is optional. 0 = full transparency, 100 = opaque.
 *
 *
 * <p>Java class for rgbColorType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rgbColorType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="r" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 * &lt;attribute name="g" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 * &lt;attribute name="b" use="required" type="{http://www.opengroup.org/xsd/archimate}rgbValueType" />
 * &lt;attribute name="a">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("f8a31d59-4f36-4cd1-a5f3-7a277ad0c0b2")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rgbColorType")
public class RgbColorType {
    @objid ("9cbb2b5f-3a4d-4f3e-97a1-67711951b1f7")
    @XmlAttribute(name = "r", required = true)
    protected short r;

    @objid ("ae73010d-0d59-4647-8815-1bb426f75499")
    @XmlAttribute(name = "g", required = true)
    protected short g;

    @objid ("31914e12-d0d7-4015-a08c-a124bf39ee66")
    @XmlAttribute(name = "b", required = true)
    protected short b;

    @objid ("7a530a4d-2d62-4cb2-9e09-ac40e1976ab0")
    @XmlAttribute(name = "a")
    protected Short a;

    /**
     * Gets the value of the r property.
     */
    @objid ("46590b47-0477-4ec6-8e0b-cca69ed6fb60")
    public short getR() {
        return this.r;
    }

    /**
     * Sets the value of the r property.
     */
    @objid ("9b65e202-02b2-42ca-bdd5-6771f57cbcf5")
    public void setR(short value) {
        this.r = value;
    }

    /**
     * Gets the value of the g property.
     */
    @objid ("e9c30624-56bb-45dc-83bc-8ff298307868")
    public short getG() {
        return this.g;
    }

    /**
     * Sets the value of the g property.
     */
    @objid ("60300565-130f-4c5d-8e73-8ca946da22ad")
    public void setG(short value) {
        this.g = value;
    }

    /**
     * Gets the value of the b property.
     */
    @objid ("f05c6564-b6ed-499a-9f4a-3ab1a8dc22fa")
    public short getB() {
        return this.b;
    }

    /**
     * Sets the value of the b property.
     */
    @objid ("cff1e3c4-da2a-464f-a617-978f61fe32e3")
    public void setB(short value) {
        this.b = value;
    }

    /**
     * Gets the value of the a property.
     *
     * @return possible object is
     * {@link Short }
     */
    @objid ("46422284-7ae6-4c11-bb31-65d2816382a2")
    public Short getA() {
        return this.a;
    }

    /**
     * Sets the value of the a property.
     *
     * @param value allowed object is
     * {@link Short }
     */
    @objid ("d2b111e7-2cd7-4bde-97e1-e5be93d13600")
    public void setA(Short value) {
        this.a = value;
    }

}
