/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * A Style type for a node and a connection.
 * It is a container for style properties such as color, font.
 *
 *
 * <p>Java class for styleType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="styleType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="fillColor" type="{http://www.opengroup.org/xsd/archimate}rgbColorType" minOccurs="0"/>
 * &lt;element name="lineColor" type="{http://www.opengroup.org/xsd/archimate}rgbColorType" minOccurs="0"/>
 * &lt;element name="font" type="{http://www.opengroup.org/xsd/archimate}fontType" minOccurs="0"/>
 * &lt;group ref="{http://www.opengroup.org/xsd/archimate}grp.any"/>
 * &lt;/sequence>
 * &lt;attribute name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 * &lt;anyAttribute namespace='##other'/>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("da3b9351-0008-48e5-8ffb-ef81012060fe")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "styleType", propOrder = {
    "fillColor",
    "lineColor",
    "font",
    "any"
})
public class StyleType {
    @objid ("f5d80667-f874-4ba3-a414-2fc820e50342")
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    @objid ("726dd94f-68b9-498f-b0ae-6d3c3b72d5db")
    protected RgbColorType fillColor;

    @objid ("33e0c479-a8db-4fbc-bd18-d614e47694a2")
    protected RgbColorType lineColor;

    @objid ("59a9f7c7-a3b7-4323-b1d9-d4a95f2375a8")
    protected FontType font;

    @objid ("484aab52-4536-43f8-8614-2e123354cad2")
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    @objid ("963273a1-ac52-4f51-8708-64c60c361afe")
    @XmlAttribute(name = "lineWidth")
    protected BigInteger lineWidth;

    /**
     * Gets the value of the fillColor property.
     *
     * @return possible object is
     * {@link RgbColorType }
     */
    @objid ("2cdd2314-3af6-4609-aed7-f4f6e117460c")
    public RgbColorType getFillColor() {
        return this.fillColor;
    }

    /**
     * Sets the value of the fillColor property.
     *
     * @param value allowed object is
     * {@link RgbColorType }
     */
    @objid ("9e60d471-e7ad-454b-9c3b-982a7ff4c2a1")
    public void setFillColor(RgbColorType value) {
        this.fillColor = value;
    }

    /**
     * Gets the value of the lineColor property.
     *
     * @return possible object is
     * {@link RgbColorType }
     */
    @objid ("0938121b-cdaf-4916-b161-d7c7795c4888")
    public RgbColorType getLineColor() {
        return this.lineColor;
    }

    /**
     * Sets the value of the lineColor property.
     *
     * @param value allowed object is
     * {@link RgbColorType }
     */
    @objid ("eca70a75-eeae-4c1b-85b7-bf9e5e8bf8dc")
    public void setLineColor(RgbColorType value) {
        this.lineColor = value;
    }

    /**
     * Gets the value of the font property.
     *
     * @return possible object is
     * {@link FontType }
     */
    @objid ("001e447d-eeed-4ece-8b1e-7cc42655fc2d")
    public FontType getFont() {
        return this.font;
    }

    /**
     * Sets the value of the font property.
     *
     * @param value allowed object is
     * {@link FontType }
     */
    @objid ("05b78a0b-5fc5-4ee2-824f-d85998b6b973")
    public void setFont(FontType value) {
        this.font = value;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    @objid ("0f78b639-ceb1-42d3-a097-b89114da8455")
    public List<Object> getAny() {
        if (this.any == null) {
            this.any = new ArrayList<>();
        }
        return this.any;
    }

    /**
     * Gets the value of the lineWidth property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    @objid ("c3d8a32b-7fe2-485c-a7dc-3fa99da73afe")
    public BigInteger getLineWidth() {
        return this.lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     *
     * @param value allowed object is
     * {@link BigInteger }
     */
    @objid ("ec21e587-5cf9-46d2-aa54-d1794dc26e04")
    public void setLineWidth(BigInteger value) {
        this.lineWidth = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and
     * the value is the string value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     *
     * @return always non-null
     */
    @objid ("71932497-98da-4a90-bdc9-2a51cdc5887a")
    public Map<QName, String> getOtherAttributes() {
        return this.otherAttributes;
    }

}
