/*
 * Copyright 2013-2025 Docaposte
 *
 * This file is part of Modelio.
 *
 * Modelio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Modelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Modelio.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.07 at 10:05:09 AM CEST
//
package org.modelio.archimate.exchange.v21.xmlmodel;

import com.modeliosoft.modelio.javadesigner.annotations.objid;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for viewpointsEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="viewpointsEnum">
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Introductory"/>
 * &lt;enumeration value="Organization"/>
 * &lt;enumeration value="Actor Co-operation"/>
 * &lt;enumeration value="Business Function"/>
 * &lt;enumeration value="Business Process"/>
 * &lt;enumeration value="Business Process Co-operation"/>
 * &lt;enumeration value="Product"/>
 * &lt;enumeration value="Application Behavior"/>
 * &lt;enumeration value="Application Co-operation"/>
 * &lt;enumeration value="Application Structure"/>
 * &lt;enumeration value="Application Usage"/>
 * &lt;enumeration value="Infrastructure"/>
 * &lt;enumeration value="Infrastructure Usage"/>
 * &lt;enumeration value="Implementation and Deployment"/>
 * &lt;enumeration value="Information Structure"/>
 * &lt;enumeration value="Service Realization"/>
 * &lt;enumeration value="Layered"/>
 * &lt;enumeration value="Landscape Map"/>
 * &lt;enumeration value="Stakeholder"/>
 * &lt;enumeration value="Goal Realization"/>
 * &lt;enumeration value="Goal Contribution"/>
 * &lt;enumeration value="Principles"/>
 * &lt;enumeration value="Requirements Realization"/>
 * &lt;enumeration value="Motivation"/>
 * &lt;enumeration value="Project"/>
 * &lt;enumeration value="Migration"/>
 * &lt;enumeration value="Implementation and Migration"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@objid ("53d63f2c-f246-4d5a-ad18-880a039607af")
@XmlType(name = "viewpointsEnum")
@XmlEnum
public enum ViewpointsEnum {
    @objid ("01bdd3ad-51f6-43a3-a342-2129397c076d")
    @XmlEnumValue("Introductory")
    INTRODUCTORY("Introductory"),
    @objid ("7af7d72e-3039-444b-afdb-f0f52b0b16b8")
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),
    @objid ("4d736800-9cbd-4990-9bf4-5e845121ccbe")
    @XmlEnumValue("Actor Co-operation")
    ACTOR_CO_OPERATION("Actor Co-operation"),
    @objid ("b99814c2-0651-4527-9f7e-5534a9a07d41")
    @XmlEnumValue("Business Function")
    BUSINESS_FUNCTION("Business Function"),
    @objid ("78e18c1b-2441-4bc0-b5a7-07d2fc1019e8")
    @XmlEnumValue("Business Process")
    BUSINESS_PROCESS("Business Process"),
    @objid ("689a2bc4-e668-452d-84f1-25d98bfd3bae")
    @XmlEnumValue("Business Process Co-operation")
    BUSINESS_PROCESS_CO_OPERATION("Business Process Co-operation"),
    @objid ("5b8156ac-d1bb-4e67-a70b-73d2f505bac5")
    @XmlEnumValue("Product")
    PRODUCT("Product"),
    @objid ("e8f18f84-13a2-49dc-b52f-d59f7cd8323f")
    @XmlEnumValue("Application Behavior")
    APPLICATION_BEHAVIOR("Application Behavior"),
    @objid ("5389bc43-6078-4022-b620-2b5460f75a91")
    @XmlEnumValue("Application Co-operation")
    APPLICATION_CO_OPERATION("Application Co-operation"),
    @objid ("afec7971-8229-4495-b56d-985cc16f9289")
    @XmlEnumValue("Application Structure")
    APPLICATION_STRUCTURE("Application Structure"),
    @objid ("3f13a281-276a-4133-b28b-6741f30f0bcb")
    @XmlEnumValue("Application Usage")
    APPLICATION_USAGE("Application Usage"),
    @objid ("853a0213-17bf-4198-a65f-d37ca8b19835")
    @XmlEnumValue("Infrastructure")
    INFRASTRUCTURE("Infrastructure"),
    @objid ("1c78cd27-720e-4bcd-a32a-0387526c1331")
    @XmlEnumValue("Infrastructure Usage")
    INFRASTRUCTURE_USAGE("Infrastructure Usage"),
    @objid ("3d8eada5-3a54-44d5-a9e6-058243006df3")
    @XmlEnumValue("Implementation and Deployment")
    IMPLEMENTATION_AND_DEPLOYMENT("Implementation and Deployment"),
    @objid ("613bf233-f801-414d-b8d3-d7fd8fcc93dd")
    @XmlEnumValue("Information Structure")
    INFORMATION_STRUCTURE("Information Structure"),
    @objid ("fe09a3a0-7d38-4dfb-938c-2a5c65d2ef86")
    @XmlEnumValue("Service Realization")
    SERVICE_REALIZATION("Service Realization"),
    @objid ("728c3f4f-552a-4553-bba2-14716de941bb")
    @XmlEnumValue("Layered")
    LAYERED("Layered"),
    @objid ("88a81c82-e014-4046-bde1-4338d007ed8a")
    @XmlEnumValue("Landscape Map")
    LANDSCAPE_MAP("Landscape Map"),
    @objid ("39177298-c03e-42e4-8e56-72e8ba094f33")
    @XmlEnumValue("Stakeholder")
    STAKEHOLDER("Stakeholder"),
    @objid ("0602f1de-5559-48f0-8a9e-dc20e9726d33")
    @XmlEnumValue("Goal Realization")
    GOAL_REALIZATION("Goal Realization"),
    @objid ("4e6084e3-51b0-4389-8195-c5d79bc135a4")
    @XmlEnumValue("Goal Contribution")
    GOAL_CONTRIBUTION("Goal Contribution"),
    @objid ("ceb387ec-db62-48f0-9898-021c0d78f23e")
    @XmlEnumValue("Principles")
    PRINCIPLES("Principles"),
    @objid ("bad5811f-fd9d-4350-acde-c1e925f5334f")
    @XmlEnumValue("Requirements Realization")
    REQUIREMENTS_REALIZATION("Requirements Realization"),
    @objid ("64f98382-a5e0-483d-8193-2e919281349d")
    @XmlEnumValue("Motivation")
    MOTIVATION("Motivation"),
    @objid ("5e191c4b-892a-433d-afd6-e7d4f809e7ec")
    @XmlEnumValue("Project")
    PROJECT("Project"),
    @objid ("f2ffe1b8-f008-4d47-a229-ec51a9c9e69b")
    @XmlEnumValue("Migration")
    MIGRATION("Migration"),
    @objid ("72b2ccb7-e813-454c-b5ea-8265567bbd5c")
    @XmlEnumValue("Implementation and Migration")
    IMPLEMENTATION_AND_MIGRATION("Implementation and Migration");

    @objid ("ed1f05a2-c366-40ee-81a3-8a3269d6e06e")
    private final String value;

    @objid ("bb1c1efe-3ec5-4542-9923-05458b9bfcaa")
    ViewpointsEnum(String v) {
        this.value = v;
    }

    @objid ("99022108-3367-4ac2-82f5-76cb23e281c3")
    public String value() {
        return this.value;
    }

    @objid ("3b157d7f-5383-46e9-8e11-b37c6c3769da")
    public static ViewpointsEnum fromValue(String v) {
        for (ViewpointsEnum c: ViewpointsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);

    }

}
