output.. = bin/
bin.includes = META-INF/,\
               .,\
               res/,\
               plugin.xml,\
               e4model/,\
               plugin.properties,plugin_fr.properties,\
               icons/
javacSource = 17
javacTarget = 17
source.. = src/
